// Generated by scripts/process-illustrations.mjs. Do not edit by hand.
// The founder's illustrations (repo illustrator/), cut out like the web copies, as resolution-aware PNGs in
// assets/illustrations/ (1x 240 px, 2.0x 480 px, 3.0x 720 px).

/// Illustration names: the same keys as the web (`<Illustration name>` / `<EmptyState art>` in @kalks/ui).
enum KIllustrationName {
  welcome('assets/illustrations/welcome.png', 0.6971),
  security('assets/illustrations/security.png', 1.0962),
  market('assets/illustrations/market.png', 1.0000),
  kycPending('assets/illustrations/kycPending.png', 1.0097),
  kycApproved('assets/illustrations/kycApproved.png', 0.9887),
  depositCredited('assets/illustrations/depositCredited.png', 0.7266),
  withdrawalProcessing('assets/illustrations/withdrawalProcessing.png', 1.4670),
  emptyHistory('assets/illustrations/emptyHistory.png', 1.5063),
  emptyPosition('assets/illustrations/emptyPosition.png', 1.6377),
  connectionLost('assets/illustrations/connectionLost.png', 1.3364),
  mascot('assets/illustrations/mascot.png', 0.6050),
  maintenance('assets/illustrations/maintenance.png', 1.5000),
  copyTrading('assets/illustrations/copyTrading.png', 1.5000),
  emptyWatchlist('assets/illustrations/emptyWatchlist.png', 1.5000),
  pammFunds('assets/illustrations/pammFunds.png', 1.3333),
  propChallenge('assets/illustrations/propChallenge.png', 1.5000),
  propPassed('assets/illustrations/propPassed.png', 1.0000),
  rewards('assets/illustrations/rewards.png', 1.1934),
  partnerIb('assets/illustrations/partnerIb.png', 1.5000),
  marketClosed('assets/illustrations/marketClosed.png', 1.3333);

  const KIllustrationName(this.asset, this.aspect);

  /// Asset path of the 1x file (Flutter picks 2.0x / 3.0x by the screen density).
  final String asset;

  /// Width / height.
  final double aspect;
}
