// Bundles the web terminal's own indicator code into the app's chart page, so the numbers and the drawing match
// Ezymex Trader on the web exactly (no Dart rewrite of the maths):
//   apps/terminal/lib/indicators.ts                        the 35 indicators (pure maths, typed params / outputs)
//   apps/terminal/components/chart/indicators/band-fill.ts  cloud / band fills (a lightweight-charts primitive)
//   apps/terminal/components/chart/indicators/layer.ts      draws instances on a chart: overlays, sub-panes, levels
// Output:
//   assets/chart/indicators.bundle.js   window.EzymexInd = { createIndicatorLayer, INDICATOR_LIST, … } for chart.html
//   assets/chart/indicators.json        the registry (names, categories, params, outputs, levels) for the Dart menus
// Run from the repo root after the web files change:  node apps/mobile/tool/build_chart_indicators.mjs
// Uses the repo's own TypeScript (node_modules/typescript): no extra tools.
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../../..');
const require = createRequire(resolve(repo, 'package.json'));
const ts = require('typescript');

const term = resolve(repo, 'apps/terminal');
const files = {
  indicators: resolve(term, 'lib/indicators.ts'),
  'band-fill': resolve(term, 'components/chart/indicators/band-fill.ts'),
  layer: resolve(term, 'components/chart/indicators/layer.ts'),
};
// import specifiers -> modules of this bundle (type-only imports are erased by the transpiler)
const alias = { '@/lib/indicators': 'indicators', './band-fill': 'band-fill' };

const js = {};
for (const [name, file] of Object.entries(files)) {
  const src = readFileSync(file, 'utf8');
  const out = ts.transpileModule(src, {
    fileName: file,
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2019, verbatimModuleSyntax: false, esModuleInterop: false },
  });
  js[name] = out.outputText;
}

const body = Object.entries(js)
  .map(([name, code]) => `  defs[${JSON.stringify(name)}] = function (module, exports, require) {\n${code}\n  };`)
  .join('\n');

const bundle = `/* GENERATED by apps/mobile/tool/build_chart_indicators.mjs from apps/terminal (lib/indicators.ts,
   components/chart/indicators/{layer,band-fill}.ts). Do not edit: change the web files and run the tool again. */
(function () {
  "use strict";
  var defs = {};
  var cache = {};
  var alias = ${JSON.stringify(alias)};
  function req(name) {
    if (name === "lightweight-charts") return window.LightweightCharts;
    var key = alias[name] || name;
    if (cache[key]) return cache[key].exports;
    var module = { exports: {} };
    cache[key] = module;
    defs[key](module, module.exports, req);
    return module.exports;
  }
${body}
  var ind = req("indicators");
  var layer = req("layer");
  window.EzymexInd = {
    createIndicatorLayer: layer.createIndicatorLayer,
    fmtValue: layer.fmtValue,
    INDICATOR_LIST: ind.INDICATOR_LIST,
    INDICATOR_DEFS: ind.INDICATOR_DEFS,
    makeInstance: ind.makeInstance,
    migrateIndicators: ind.migrateIndicators,
    normalizeParams: ind.normalizeParams,
    indicatorLabel: ind.indicatorLabel,
    calcIndicator: ind.calcIndicator,
  };
})();
`;
writeFileSync(resolve(here, '../assets/chart/indicators.bundle.js'), bundle);

// the registry for Dart: everything but the kernels
const mod = { exports: {} };
vm.runInNewContext(js.indicators, { module: mod, exports: mod.exports, require, Math, Number, String, Object, Array, JSON, isFinite, NaN, Infinity });
const { INDICATOR_LIST, INDICATOR_CATEGORIES, defaultParams, COLOR_TOKENS, SOURCES, SOURCE_LABEL } = mod.exports;
const registry = {
  categories: INDICATOR_CATEGORIES,
  colors: COLOR_TOKENS,
  sources: SOURCES.map((s) => ({ value: s, label: SOURCE_LABEL[s] })),
  indicators: INDICATOR_LIST.map((d) => ({
    type: d.type,
    name: d.name,
    short: d.short,
    category: d.category,
    pane: d.pane,
    description: d.description,
    params: d.params.map((p) => ({ ...p })),
    outputs: d.outputs.map((o) => ({ key: o.key, label: o.label, kind: o.kind, color: o.color, ...(o.width ? { width: o.width } : {}), ...(o.histColor ? { histColor: o.histColor } : {}) })),
    levels: d.levels ? d.levels(defaultParams(d.type)) : [],
  })),
};
writeFileSync(resolve(here, '../assets/chart/indicators.json'), JSON.stringify(registry) + '\n');
console.log(`indicators.bundle.js: ${(bundle.length / 1024).toFixed(1)} KB · indicators.json: ${registry.indicators.length} indicators`);
