import {
  LayoutGrid,
  Layers,
  Wallet,
  PieChart,
  Handshake,
  Copy,
  Trophy,
  Gift,
  Code2,
  GraduationCap,
  UserRound,
  LifeBuoy,
  Newspaper,
  CalendarDays,
  Globe2,
  PlusCircle,
  ArrowDownToLine,
  ArrowUpFromLine,
  ArrowLeftRight,
  History,
  BarChart3,
  BookText,
  FileText,
  Users,
  Network,
  Coins,
  Link2,
  Banknote,
  Compass,
  Repeat,
  Landmark,
  LineChart,
  Crown,
  Target,
  Medal,
  Percent,
  KeyRound,
  Webhook,
  Workflow,
  FlaskConical,
  Store,
  Award,
  BookOpen,
  Bot,
  ShieldCheck,
  BadgeCheck,
  Eye,
  SlidersHorizontal,
} from "lucide-react";
import type { NavModule } from "@kalks/ui";
import { IS_DEMO } from "@kalks/mock/mode";

export const CRM_NAV: NavModule[] = [
  {
    key: "dashboard",
    label: "Dashboard",
    icon: LayoutGrid,
    href: "/",
    match: ["/", "/markets", "/news", "/calendar"],
    section: "main",
    sub: [
      { href: "/", label: "Overview", icon: LayoutGrid },
      { href: "/markets", label: "Markets", icon: Globe2 },
      { href: "/news", label: "News", icon: Newspaper },
      { href: "/calendar", label: "Calendar", icon: CalendarDays },
    ],
  },
  {
    key: "accounts",
    label: "Accounts",
    icon: Layers,
    href: "/accounts",
    section: "main",
    sub: [
      { href: "/accounts", label: "My accounts", icon: Layers },
      { href: "/accounts/new", label: "Open account", icon: PlusCircle },
    ],
  },
  {
    key: "wallet",
    label: "Wallet",
    icon: Wallet,
    href: "/wallet",
    section: "main",
    sub: [
      { href: "/wallet", label: "Overview", icon: Wallet },
      { href: "/wallet/deposit", label: "Deposit", icon: ArrowDownToLine },
      { href: "/wallet/withdraw", label: "Withdraw", icon: ArrowUpFromLine },
      { href: "/wallet/transfer", label: "Transfer", icon: ArrowLeftRight },
      { href: "/wallet/history", label: "History", icon: History },
    ],
  },
  {
    key: "portfolio",
    label: "Portfolio",
    icon: PieChart,
    href: "/portfolio",
    section: "main",
    sub: [
      { href: "/portfolio", label: "Overview", icon: PieChart },
      { href: "/portfolio/analytics", label: "Analytics", icon: BarChart3 },
      { href: "/portfolio/history", label: "Trade history", icon: History },
      { href: "/portfolio/ledger", label: "Ledger", icon: BookText },
      { href: "/portfolio/statements", label: "Statements", icon: FileText },
    ],
  },
  {
    key: "partner",
    label: "Partner (IB)",
    icon: Handshake,
    href: "/partner",
    section: "grow",
    sub: [
      { href: "/partner", label: "Dashboard", icon: LayoutGrid },
      { href: "/partner/clients", label: "Clients", icon: Users },
      { href: "/partner/network", label: "Network", icon: Network },
      { href: "/partner/commissions", label: "Commissions", icon: Coins },
      { href: "/partner/links", label: "Links & materials", icon: Link2 },
      { href: "/partner/payouts", label: "Payouts", icon: Banknote },
    ],
  },
  {
    key: "social",
    label: "Copy & PAMM",
    icon: Copy,
    href: "/social",
    section: "grow",
    sub: [
      { href: "/social", label: "Discover", icon: Compass },
      { href: "/social/copy", label: "Copy trading", icon: Repeat },
      { href: "/social/pamm", label: "PAMM funds", icon: Landmark },
      { href: "/social/investments", label: "My investments", icon: LineChart },
      { href: "/social/master", label: "Become a master", icon: Crown },
    ],
  },
  {
    key: "prop",
    label: "Prop Challenges",
    icon: Trophy,
    href: "/prop",
    section: "grow",
    sub: [
      { href: "/prop", label: "Challenges", icon: Target },
      { href: "/prop/mine", label: "My challenges", icon: Trophy },
      { href: "/prop/payouts", label: "Payouts", icon: Banknote },
      { href: "/prop/certificates", label: "Certificates", icon: Award },
    ],
  },
  {
    key: "rewards",
    label: "Contests & Rewards",
    icon: Gift,
    href: "/rewards",
    section: "grow",
    sub: [
      { href: "/rewards", label: "Contests", icon: Medal },
      { href: "/rewards/loyalty", label: "Loyalty", icon: Gift },
      { href: "/rewards/cashback", label: "Cashback", icon: Percent },
    ],
  },
  {
    key: "developer",
    label: "API & Algo",
    icon: Code2,
    href: "/developer",
    section: "build",
    sub: [
      { href: "/developer", label: "API keys", icon: KeyRound },
      { href: "/developer/webhooks", label: "Webhooks", icon: Webhook },
      { href: "/developer/strategies", label: "Strategy builder", icon: Workflow },
      { href: "/developer/backtests", label: "Backtests", icon: FlaskConical },
      { href: "/developer/marketplace", label: "Marketplace", icon: Store },
      { href: "/developer/docs", label: "Docs", icon: BookOpen },
    ],
  },
  {
    key: "academy",
    label: "Academy & AI Coach",
    icon: GraduationCap,
    href: "/academy",
    section: "learn",
    sub: [
      { href: "/academy", label: "Courses", icon: GraduationCap },
      { href: "/academy/glossary", label: "Glossary", icon: BookOpen },
      { href: "/academy/progress", label: "My progress", icon: Award },
      { href: "/academy/coach", label: "AI Coach", icon: Bot },
    ],
  },
  {
    key: "profile",
    label: "Profile & Security",
    icon: UserRound,
    href: "/profile",
    section: "account",
    sub: [
      { href: "/profile", label: "Profile", icon: UserRound },
      { href: "/profile/security", label: "Security", icon: ShieldCheck },
      { href: "/profile/verification", label: "Verification", icon: BadgeCheck },
      { href: "/profile/viewers", label: "View-only access", icon: Eye },
      { href: "/profile/preferences", label: "Preferences", icon: SlidersHorizontal },
    ],
  },
  { key: "support", label: "Support", icon: LifeBuoy, href: "/support", section: "account" },
];

/** Live builds list every module, like the demo, without the demo's mock count badges. */
export const LIVE_NAV: NavModule[] = CRM_NAV.map((m) => ({
  ...m,
  badge: undefined, // demo badges are mock counts
  sub: m.sub?.map((s) => ({ ...s, badge: undefined })),
}));

/** Navigation for this build. */
export const NAV: NavModule[] = IS_DEMO ? CRM_NAV : LIVE_NAV;

/** Flattened entries for the ⌘K palette ("Soon" modules are grouped as Coming soon in live builds). */
export const CRM_COMMANDS = NAV.flatMap((m) =>
  (m.sub ?? [{ href: m.href, label: m.label, icon: m.icon }]).map((s) => ({
    group: m.label,
    label: s.label,
    href: s.href,
    Icon: s.icon ?? m.icon,
  })),
);
