// Generated by apps/mobile/scripts/process-illustrations.mjs (web copies). Do not edit by hand.
/* eslint-disable */

export type IllustrationName = "welcome" | "security" | "market" | "kycPending" | "kycApproved" | "depositCredited" | "withdrawalProcessing" | "emptyHistory" | "emptyPosition" | "connectionLost" | "mascot" | "maintenance" | "copyTrading" | "emptyWatchlist" | "pammFunds" | "propChallenge" | "propPassed" | "rewards" | "partnerIb" | "marketClosed";

/** Files in public/illustrations as [suffix, px width] (smallest first), the size of the default file (width / height
 *  give the aspect for layout without shift) and a content hash that versions the URLs (served as immutable). */
export const WEB_ILLUSTRATIONS: Record<IllustrationName, { files: readonly (readonly [string, number])[]; w: number; h: number; v: string }> = {
  welcome: { files: [["-sm",320],["",640],["@2x",1017]], w: 640, h: 918, v: "b47f1dfd85" },
  security: { files: [["-sm",320],["",640],["@2x",1185]], w: 640, h: 584, v: "27c726e91c" },
  market: { files: [["-sm",320],["",640],["@2x",1254]], w: 640, h: 640, v: "5395bcccba" },
  kycPending: { files: [["-sm",320],["",640],["@2x",1254]], w: 640, h: 634, v: "1596c7e9d3" },
  kycApproved: { files: [["-sm",320],["",640],["@2x",1227]], w: 640, h: 647, v: "c385a51461" },
  depositCredited: { files: [["-sm",320],["",640],["@2x",869]], w: 640, h: 881, v: "9257121902" },
  withdrawalProcessing: { files: [["-sm",320],["",640],["@2x",1280]], w: 640, h: 436, v: "6a072d6cd4" },
  emptyHistory: { files: [["-sm",320],["",640],["@2x",1280]], w: 640, h: 425, v: "cdc02b769f" },
  emptyPosition: { files: [["-sm",320],["",640],["@2x",1280]], w: 640, h: 391, v: "30c850460f" },
  connectionLost: { files: [["-sm",320],["",640],["@2x",1280]], w: 640, h: 479, v: "bed5829f8b" },
  mascot: { files: [["-sm",320],["",507]], w: 507, h: 838, v: "2dac298b1f" },
  maintenance: { files: [["-sm",320],["",640],["@2x",1280]], w: 640, h: 427, v: "79bd820307" },
  copyTrading: { files: [["-sm",320],["",640],["@2x",1280]], w: 640, h: 427, v: "7e47355323" },
  emptyWatchlist: { files: [["-sm",320],["",640],["@2x",1280]], w: 640, h: 427, v: "46f3064360" },
  pammFunds: { files: [["-sm",320],["",640],["@2x",1280]], w: 640, h: 480, v: "1970c37c4a" },
  propChallenge: { files: [["-sm",320],["",640],["@2x",1280]], w: 640, h: 427, v: "a4ec8e3da7" },
  propPassed: { files: [["-sm",320],["",640],["@2x",1254]], w: 640, h: 640, v: "94b1d616ba" },
  rewards: { files: [["-sm",320],["",640],["@2x",1166]], w: 640, h: 536, v: "4eb83809c7" },
  partnerIb: { files: [["-sm",320],["",640],["@2x",1280]], w: 640, h: 427, v: "dea6ac2877" },
  marketClosed: { files: [["-sm",320],["",640],["@2x",1280]], w: 640, h: 480, v: "748c4adcba" },
};
