// Generated by packages/ui/scripts/gen-world-dots.mjs — do not edit by hand.
// 2343 land dots of a 128×63 grid (step 7.5) over a 960×470 Equal Earth map fitted to world-atlas 110m.

export const WORLD_W = 960;
export const WORLD_H = 470;
export const WORLD_STEP = 7.5;
/** geoEqualEarth().fitSize([W, H], land): scale and translate. */
export const WORLD_SCALE = 179.1984035352986;
export const WORLD_TRANSLATE: [number, number] = [480, 233.93069668213545];
/** Per grid row: run lengths (base 36) alternating sea / land, starting with sea. */
export const WORLD_ROWS: readonly string[] = ["5.1.11.4.2.b.6.2.h.1.11.4.1","0.6.2.1.q.2.3.1.1.1.8.8.i.1.5.8.s.2.4.2.1","0.k.4.6.1.8.2.1.1.1.1.3.3.7.a.4.7.1.1.o.1.2.4.6.1.4.1.3.1","0.k.1.l.3.3.2.4.4.2.7.6.1.12.1.f","0.f.5.j.4.2.6.2.c.4.1.15.4.d","0.4.3.1.1.1.a.2.4.c.5.2.1.1.j.3.1.x.2.1.2.1.9.2.4.4","0.1.6.1.j.c.3.5.f.1.3.1.3.x.5.2.a.1.7","0.1.4.1.l.d.1.7.d.1.1.1.1.14.4.1.i","r.j.g.1.1.15.n","q.i.2.2.f.17.m","q.j.j.9.1.5.1.q.m","p.h.j.4.2.1.1.4.4.2.1.p.3.1.j","p.f.l.3.5.b.1.l.1.2.3.1.j","o.f.m.3.7.1.1.7.1.l.2.1.n","o.f.p.4.8.r.2.1.2.2.i","p.d.n.7.8.s.3.1.k","p.c.o.9.1.2.1.v.n","p.7.4.1.n.k.1.o.n","p.1.1.4.5.1.m.m.1.n.n","r.3.t.h.1.5.5.j.m","r.3.6.1.l.j.1.7.3.7.1.8.o","r.3.2.2.3.1.k.j.1.6.5.5.2.5.r","s.5.7.1.h.j.2.5.6.3.4.4.5.1.l","v.2.p.k.1.3.8.3.4.5.4.1.l","w.2.o.n.9.2.7.4.4.1.k","x.1.4.1.j.l.c.1.7.1.1.2.5.1.j","11.1.1.3.h.n.9.1.9.1.q","10.7.g.n.q.1.j","10.9.f.4.2.f.j.1.4.2.l","10.a.l.e.i.2.4.1.m","10.a.l.d.j.2.2.4.l","z.c.k.c.l.1.2.3.5.1.g","z.e.j.a.m.2.2.2.1.1.5.2.d","z.g.h.a.n.1.b.3.2.1.9","z.h.h.9.o.1.b.3.b","10.f.i.9.10.1.1.1.4.1.6","10.f.i.9.1e","11.d.j.9.3.1.s.2.2.1.d","11.d.i.a.3.1.q.4.2.1.d","13.b.i.9.2.2.q.6.1.1.d","13.b.i.8.4.1.p.9.d","14.a.j.7.3.2.n.c.5.1.6","14.8.l.7.3.1.n.d.c","14.7.m.6.s.d.c","14.8.l.6.s.d.c","14.7.n.4.t.c.d","14.7.n.3.t.4.3.6.d","14.5.1l.1.6.4.f","14.6.1r.4.f","5.1.z.3.24.1.7","5.1.z.3.1u.1.7.1.9","5.1.z.3.20.1.b","15.3.2c","16.2.14.1.17","16.2.2c","18.1.2b","3k","3k","3k","0.b.10.1.r.4.1.1.3.h.r","0.j.r.3.c.j.1.o.n","0.j.b.g.b.18.b.g","0.t.4.22.3.i"];
