"use client";

import * as React from "react";
import Link from "next/link";
import { AlertTriangle, CalendarClock, Download, FileCheck2, History, Landmark, ShieldCheck, Upload } from "lucide-react";
import { toast } from "sonner";
import {
  Avatar,
  Button,
  Card,
  CardHeader,
  Chip,
  CopyButton,
  DataTable,
  IconButton,
  KpiCard,
  PageHeader,
  Reveal,
  StatusChip,
  Tooltip,
  formatDateTime,
  formatNumber,
  shortHash,
  type Column,
} from "@ezymex/ui";
import { PEOPLE } from "@ezymex/mock";
import { ANL_REG_HISTORY, ANL_REG_REPORTS, anlHash, type AnlRegHistory } from "@ezymex/mock/admin-growth-analytics";
import { RegReportCard, type GeneratedExport } from "@/components/analytics/reg-report-card";
import { IS_DEMO } from "@ezymex/mock/mode";
import { LiveRegulatory } from "@/components/reports/live-ops";

const FMT_TONE = { CSV: "neutral", XML: "info", XLSX: "up" } as const;

function DemoRegulatoryPage() {
  const [history, setHistory] = React.useState<AnlRegHistory[]>(ANL_REG_HISTORY);
  const seq = React.useRef(0);

  const onGenerated = React.useCallback((e: GeneratedExport) => {
    seq.current += 1;
    const n = seq.current;
    setHistory((h) => [
      {
        id: `EXP-${48_210 + n}`,
        report: e.report,
        period: e.period,
        format: e.format,
        by: PEOPLE[4]!,
        at: new Date().toISOString(),
        rows: e.rows,
        size: e.rows > 5000 ? `${((e.rows * 236) / 1_048_576).toFixed(1)} MB` : `${Math.max(1, Math.round((e.rows * 900) / 1024))} KB`,
        hash: anlHash(5000 + n + e.rows),
        status: "completed",
      },
      ...h,
    ]);
  }, []);

  const cols: Column<AnlRegHistory>[] = [
    { key: "id", header: "Export", cell: (r) => <span className="font-mono text-[12px] text-fg-2">{r.id}</span> },
    {
      key: "report",
      header: "Report",
      cell: (r) => (
        <div className="min-w-0">
          <div className="truncate text-[13.5px] font-medium">{r.report}</div>
          <div className="text-[11.5px] text-fg-3">{r.period}</div>
        </div>
      ),
    },
    { key: "fmt", header: "Format", cell: (r) => <Chip size="sm" tone={FMT_TONE[r.format]}>{r.format}</Chip> },
    {
      key: "by",
      header: "Generated by",
      hideOn: "lg",
      cell: (r) => (
        <div className="flex items-center gap-2">
          <Avatar src={r.by.photo} name={r.by.name} size={24} />
          <span className="truncate text-[12.5px] text-fg-2">{r.by.name}</span>
        </div>
      ),
    },
    { key: "at", header: "Time (GMT+3)", sort: (r) => r.at, cell: (r) => <span className="k-num text-[12.5px] text-fg-2">{formatDateTime(r.at)}</span> },
    { key: "rows", header: "Rows", align: "right", sort: (r) => r.rows, cell: (r) => <span className="k-num">{formatNumber(r.rows, 0)}</span>, hideOn: "md" },
    { key: "size", header: "Size", align: "right", cell: (r) => <span className="k-num text-fg-2">{r.status === "failed" ? "—" : r.size}</span>, hideOn: "md" },
    {
      key: "hash",
      header: "SHA-256",
      cell: (r) =>
        r.status === "failed" ? (
          <span className="text-[12px] text-fg-3">—</span>
        ) : (
          <span className="flex items-center gap-1">
            <Tooltip content={<span className="font-mono text-[10.5px]">{r.hash}</span>}>
              <span className="font-mono text-[12px] text-fg-2">{shortHash(r.hash, 8, 6)}</span>
            </Tooltip>
            <CopyButton value={r.hash} label="Hash" />
          </span>
        ),
    },
    { key: "st", header: "Status", cell: (r) => <StatusChip status={r.status} /> },
    {
      key: "dl",
      header: "",
      align: "right",
      cell: (r) =>
        r.status === "failed" ? (
          <Button size="xs" variant="outline" onClick={() => toast.success(`Retrying ${r.id}`, { description: `${r.report} · ${r.period}` })}>
            Retry
          </Button>
        ) : (
          <IconButton size="sm" aria-label="Download" onClick={() => toast.success("Download started", { description: `${r.id}.${r.format.toLowerCase()} · ${r.size}` })}>
            <Download />
          </IconButton>
        ),
    },
  ];

  return (
    <div className="pb-16">
      <PageHeader
        title="Regulatory exports"
        subtitle="Generate, sign and archive regulator submissions · files are SHA-256 hashed and retained for 7 years"
        actions={
          <>
            <Link href="/analytics/scheduled">
              <Button variant="surface">
                <CalendarClock /> Automate
              </Button>
            </Link>
            <Button variant="ember" onClick={() => toast.success("Submission package uploaded", { description: "3 files sent to FSA Seychelles portal via SFTP · receipt #FSA-2026-09-24-0381" })}>
              <Upload /> Submit to regulator
            </Button>
          </>
        }
      />

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <KpiCard label="Due in 7 days" icon={<CalendarClock />} value={<span className="k-num">3</span>} chip="Next: Transaction report · 09:00" chipTone="warn" />
        <KpiCard label="Submitted · Sep" icon={<FileCheck2 />} value={<span className="k-num">148</span>} chip="100% on time" chipTone="up" delay={0.05} />
        <KpiCard label="Open STRs" icon={<AlertTriangle />} value={<span className="k-num">2</span>} chip="MLRO review" chipTone="down" href="/clients/aml" delay={0.1} />
        <KpiCard label="Licences reporting" icon={<Landmark />} value={<span className="k-num">3</span>} hot illustration="shield" footer={<span className="text-[11.5px] text-fg-2">FSA SC · FSC MU · FIU</span>} delay={0.15} />
      </div>

      <Reveal delay={0.1} className="mt-4">
        <div className="mb-3 mt-2 flex items-center gap-2">
          <ShieldCheck className="size-4 text-fg-3" />
          <h2 className="text-[15px] font-medium">Report catalogue</h2>
          <span className="text-[12.5px] text-fg-3">· pick a period and format, then generate</span>
        </div>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
          {ANL_REG_REPORTS.map((r) => (
            <RegReportCard key={r.id} report={r} onGenerated={onGenerated} />
          ))}
        </div>
      </Reveal>

      <Reveal delay={0.15} className="mt-4">
        <Card>
          <CardHeader title="Export history" subtitle="Immutable archive · hashes verifiable against the audit log" icon={<History />} action={<Link href="/security"><Button size="sm" variant="surface">Audit log</Button></Link>} />
          <div className="mt-4 px-4 pb-5 sm:px-6">
            <DataTable columns={cols} rows={history} pageSize={8} dense search={(r) => `${r.id} ${r.report} ${r.period} ${r.hash}`} exportName="regulatory-export-history" rowKey={(r) => r.id} />
          </div>
        </Card>
      </Reveal>
    </div>
  );
}

/** Live builds: the reports service (/api/reports). Demo builds: mock data. */
export default function RegulatoryPage() {
  return IS_DEMO ? <DemoRegulatoryPage /> : <LiveRegulatory />;
}
