//! First-start seed data. Every insert is `ON CONFLICT DO NOTHING`, so staff edits are never overwritten
//! and a seed row an admin disabled stays disabled.
//!
//! * Underlyings: 9 FX pairs (Garman-Kohlhagen), XAU / XAG (Black-Scholes with a lease rate), USOIL /
//!   UKOIL (Black-76 on the CFD price as the forward). Contract sizes per O7. NZDUSD has no market-data
//!   symbol in config/instruments.json yet, so it is seeded **disabled**.
//! * Rates: approximate central-bank policy rates and metal lease rates (admin-editable; verify).
//! * Vol surfaces: version 1 per underlying, market-like ATM / 25D / 10D quotes for ON..3M.
//! * Module switches: tenant `kalks` (tenant #1) demo ON, live OFF, public chain OFF. Other tenants: OFF.
//! * Holidays: config/holidays/*.json (generated by scripts/gen-holidays.mjs).

use std::path::Path;

use serde::Deserialize;
use serde_json::json;
use sqlx::PgPool;

use crate::model::{Pillar, build_surface};
use crate::store;

pub struct SeedUnderlying {
    pub symbol: &'static str,
    pub name: &'static str,
    pub class: &'static str,
    pub model: &'static str,
    pub base: &'static str,
    pub quote: &'static str,
    pub calendars: &'static [&'static str],
    pub size: f64,
    pub unit: &'static str,
    pub digits: i32,
    pub pip: f64,
    pub step: f64,
    pub price_scan: f64,
    pub vol_scan: f64,
    pub enabled: bool,
    pub notes: &'static str,
    /// ATM vols ON, 1W, 2W, 1M, 2M, 3M and RR25, BF25, RR10, BF10 (decimals).
    pub atm: [f64; 6],
    pub skew: [f64; 4],
}

const FX: &str = "forex";

pub const UNDERLYINGS: &[SeedUnderlying] = &[
    SeedUnderlying { symbol: "EURUSD", name: "Euro / US Dollar", class: FX, model: "gk", base: "EUR", quote: "USD", calendars: &["EUR", "USD"], size: 10_000.0, unit: "EUR", digits: 5, pip: 0.0001, step: 0.0025, price_scan: 0.03, vol_scan: 0.03, enabled: true, notes: "", atm: [0.062, 0.066, 0.068, 0.070, 0.072, 0.073], skew: [0.002, 0.0015, 0.004, 0.005] },
    SeedUnderlying { symbol: "GBPUSD", name: "British Pound / US Dollar", class: FX, model: "gk", base: "GBP", quote: "USD", calendars: &["GBP", "USD"], size: 10_000.0, unit: "GBP", digits: 5, pip: 0.0001, step: 0.0025, price_scan: 0.03, vol_scan: 0.03, enabled: true, notes: "", atm: [0.068, 0.072, 0.074, 0.076, 0.078, 0.079], skew: [-0.003, 0.0018, -0.006, 0.006] },
    SeedUnderlying { symbol: "USDJPY", name: "US Dollar / Japanese Yen", class: FX, model: "gk", base: "USD", quote: "JPY", calendars: &["USD", "JPY"], size: 10_000.0, unit: "USD", digits: 3, pip: 0.01, step: 0.5, price_scan: 0.04, vol_scan: 0.035, enabled: true, notes: "", atm: [0.095, 0.098, 0.100, 0.102, 0.104, 0.105], skew: [-0.010, 0.003, -0.020, 0.011] },
    SeedUnderlying { symbol: "AUDUSD", name: "Australian Dollar / US Dollar", class: FX, model: "gk", base: "AUD", quote: "USD", calendars: &["AUD", "USD"], size: 10_000.0, unit: "AUD", digits: 5, pip: 0.0001, step: 0.0025, price_scan: 0.035, vol_scan: 0.035, enabled: true, notes: "", atm: [0.082, 0.086, 0.088, 0.090, 0.092, 0.093], skew: [-0.008, 0.0025, -0.015, 0.009] },
    SeedUnderlying { symbol: "USDCAD", name: "US Dollar / Canadian Dollar", class: FX, model: "gk", base: "USD", quote: "CAD", calendars: &["USD", "CAD"], size: 10_000.0, unit: "USD", digits: 5, pip: 0.0001, step: 0.0025, price_scan: 0.025, vol_scan: 0.03, enabled: true, notes: "", atm: [0.050, 0.053, 0.055, 0.056, 0.058, 0.059], skew: [0.004, 0.0015, 0.008, 0.005] },
    SeedUnderlying { symbol: "USDCHF", name: "US Dollar / Swiss Franc", class: FX, model: "gk", base: "USD", quote: "CHF", calendars: &["USD", "CHF"], size: 10_000.0, unit: "USD", digits: 5, pip: 0.0001, step: 0.0025, price_scan: 0.035, vol_scan: 0.035, enabled: true, notes: "", atm: [0.068, 0.071, 0.073, 0.075, 0.077, 0.078], skew: [-0.004, 0.002, -0.008, 0.007] },
    SeedUnderlying { symbol: "NZDUSD", name: "New Zealand Dollar / US Dollar", class: FX, model: "gk", base: "NZD", quote: "USD", calendars: &["NZD", "USD"], size: 10_000.0, unit: "NZD", digits: 5, pip: 0.0001, step: 0.0025, price_scan: 0.035, vol_scan: 0.035, enabled: false, notes: "Disabled: NZDUSD is not in config/instruments.json (no market-data feed yet). Enable once market-data lists it.", atm: [0.088, 0.091, 0.093, 0.095, 0.097, 0.098], skew: [-0.008, 0.0025, -0.015, 0.009] },
    SeedUnderlying { symbol: "EURJPY", name: "Euro / Japanese Yen", class: FX, model: "gk", base: "EUR", quote: "JPY", calendars: &["EUR", "JPY"], size: 10_000.0, unit: "EUR", digits: 3, pip: 0.01, step: 0.5, price_scan: 0.04, vol_scan: 0.035, enabled: true, notes: "", atm: [0.088, 0.092, 0.094, 0.096, 0.098, 0.099], skew: [-0.012, 0.003, -0.024, 0.012] },
    SeedUnderlying { symbol: "GBPJPY", name: "British Pound / Japanese Yen", class: FX, model: "gk", base: "GBP", quote: "JPY", calendars: &["GBP", "JPY"], size: 10_000.0, unit: "GBP", digits: 3, pip: 0.01, step: 0.5, price_scan: 0.045, vol_scan: 0.04, enabled: true, notes: "", atm: [0.098, 0.102, 0.104, 0.106, 0.108, 0.109], skew: [-0.014, 0.0035, -0.027, 0.013] },
    SeedUnderlying { symbol: "XAUUSD", name: "Gold / US Dollar", class: "metals", model: "bs", base: "XAU", quote: "USD", calendars: &["XAU"], size: 1.0, unit: "oz", digits: 2, pip: 0.01, step: 25.0, price_scan: 0.05, vol_scan: 0.05, enabled: true, notes: "Black-Scholes, q = XAU lease rate.", atm: [0.17, 0.18, 0.185, 0.19, 0.195, 0.20], skew: [0.015, 0.004, 0.030, 0.015] },
    SeedUnderlying { symbol: "XAGUSD", name: "Silver / US Dollar", class: "metals", model: "bs", base: "XAG", quote: "USD", calendars: &["XAG"], size: 50.0, unit: "oz", digits: 3, pip: 0.001, step: 0.5, price_scan: 0.08, vol_scan: 0.06, enabled: true, notes: "Black-Scholes, q = XAG lease rate.", atm: [0.28, 0.30, 0.31, 0.32, 0.325, 0.33], skew: [0.02, 0.008, 0.04, 0.025] },
    SeedUnderlying { symbol: "USOIL", name: "WTI Crude Oil", class: "energies", model: "black76", base: "OIL", quote: "USD", calendars: &["OIL"], size: 10.0, unit: "bbl", digits: 2, pip: 0.01, step: 0.5, price_scan: 0.10, vol_scan: 0.08, enabled: true, notes: "Black-76: the CFD price is used as the forward.", atm: [0.30, 0.32, 0.33, 0.34, 0.345, 0.35], skew: [-0.01, 0.008, -0.02, 0.025] },
    SeedUnderlying { symbol: "UKOIL", name: "Brent Crude Oil", class: "energies", model: "black76", base: "OIL", quote: "USD", calendars: &["OIL"], size: 10.0, unit: "bbl", digits: 2, pip: 0.01, step: 0.5, price_scan: 0.10, vol_scan: 0.08, enabled: true, notes: "Black-76: the CFD price is used as the forward. Calendar = OIL (USD); ICE Europe closures are not modelled.", atm: [0.28, 0.30, 0.31, 0.32, 0.325, 0.33], skew: [-0.01, 0.008, -0.02, 0.025] },
];

/// (ccy, rate, kind, source). Approximate; staff keep them current in the Back Office.
pub const RATES: &[(&str, f64, &str, &str)] = &[
    ("USD", 0.03625, "policy", "Fed funds target range mid (approx. seed, verify)"),
    ("EUR", 0.0200, "policy", "ECB deposit facility rate (approx. seed, verify)"),
    ("GBP", 0.0375, "policy", "BoE Bank Rate (approx. seed, verify)"),
    ("JPY", 0.0075, "policy", "BoJ short-term policy rate (approx. seed, verify)"),
    ("CHF", 0.0000, "policy", "SNB policy rate (approx. seed, verify)"),
    ("CAD", 0.0225, "policy", "BoC overnight rate target (approx. seed, verify)"),
    ("AUD", 0.0360, "policy", "RBA cash rate target (approx. seed, verify)"),
    ("NZD", 0.0225, "policy", "RBNZ official cash rate (approx. seed, verify)"),
    ("XAU", 0.0050, "lease", "Gold lease rate (approx. seed, verify)"),
    ("XAG", 0.0100, "lease", "Silver lease rate (approx. seed, verify)"),
];

pub const TENORS: [(&str, f64); 6] = [("ON", 1.0), ("1W", 7.0), ("2W", 14.0), ("1M", 30.0), ("2M", 61.0), ("3M", 91.0)];

/// Default pillars: skew scaled down at the short end.
pub fn default_pillars(u: &SeedUnderlying) -> Vec<Pillar> {
    let scale = [0.8, 0.9, 0.95, 1.0, 1.0, 1.0];
    TENORS
        .iter()
        .enumerate()
        .map(|(i, (tenor, days))| Pillar {
            tenor: tenor.to_string(),
            days: *days,
            atm: u.atm[i],
            rr25: u.skew[0] * scale[i],
            bf25: u.skew[1] * scale[i],
            rr10: Some(u.skew[2] * scale[i]),
            bf10: Some(u.skew[3] * scale[i]),
        })
        .collect()
}

#[derive(Deserialize)]
struct HolidayFile {
    calendar: String,
    holidays: Vec<HolidayEntry>,
}

#[derive(Deserialize)]
struct HolidayEntry {
    date: chrono::NaiveDate,
    name: String,
}

/// Seeds everything; returns the number of rows inserted (0 on an already seeded database).
pub async fn run(pool: &PgPool, holidays_dir: &str) -> anyhow::Result<u64> {
    let mut tx = pool.begin().await?;
    let mut n = 0u64;
    for (i, u) in UNDERLYINGS.iter().enumerate() {
        let r = sqlx::query(
            "INSERT INTO underlyings (symbol, name, asset_class, model, base_ccy, quote_ccy, calendars, contract_size, contract_unit, digits,
                pip_size, strike_step, price_scan, vol_scan, delta_convention, enabled, sort, notes)
             VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) ON CONFLICT (symbol) DO NOTHING",
        )
        .bind(u.symbol)
        .bind(u.name)
        .bind(u.class)
        .bind(u.model)
        .bind(u.base)
        .bind(u.quote)
        .bind(u.calendars.iter().map(|s| s.to_string()).collect::<Vec<_>>())
        .bind(u.size)
        .bind(u.unit)
        .bind(u.digits)
        .bind(u.pip)
        .bind(u.step)
        .bind(u.price_scan)
        .bind(u.vol_scan)
        .bind(if u.model == "black76" { "forward" } else { "spot" })
        .bind(u.enabled)
        .bind(i as i32 * 10)
        .bind(u.notes)
        .execute(&mut *tx)
        .await?;
        n += r.rows_affected();
        let has_surface: Option<i32> = sqlx::query_scalar("SELECT 1 FROM vol_surfaces WHERE symbol = $1 LIMIT 1").bind(u.symbol).fetch_optional(&mut *tx).await?;
        if has_surface.is_none() {
            let pillars = default_pillars(u);
            build_surface(&pillars).map_err(|e| anyhow::anyhow!("seed surface {} invalid: {e}", u.symbol))?;
            sqlx::query("INSERT INTO vol_surfaces (symbol, version, blend_weight, pillars, reason, published_by) VALUES ($1, 1, 0.7, $2, 'Initial seed', 'seed')")
                .bind(u.symbol)
                .bind(serde_json::to_value(&pillars)?)
                .execute(&mut *tx)
                .await?;
            n += 1;
        }
    }
    for (ccy, rate, kind, source) in RATES {
        let r = sqlx::query("INSERT INTO rates (ccy, rate, kind, source) VALUES ($1,$2,$3,$4) ON CONFLICT (ccy) DO NOTHING")
            .bind(ccy)
            .bind(rate)
            .bind(kind)
            .bind(source)
            .execute(&mut *tx)
            .await?;
        if r.rows_affected() > 0 {
            sqlx::query("INSERT INTO rate_history (ccy, rate, as_of, reason, changed_by) VALUES ($1, $2, CURRENT_DATE, 'Initial seed', 'seed')")
                .bind(ccy)
                .bind(rate)
                .execute(&mut *tx)
                .await?;
            n += 1;
        }
    }
    // Tenant #1: demo and live on (founder decision 2026-10-02: the team tests with real money; clients still need
    // KYC + options disclosure + quiz, and per-client contract limits apply). Every other tenant has no row = OFF.
    n += sqlx::query("INSERT INTO tenant_settings (tenant, enabled_demo, enabled_live, public_chain) VALUES ('kalks', true, true, false) ON CONFLICT DO NOTHING")
        .execute(&mut *tx)
        .await?
        .rows_affected();
    // The platform default row, with the order book's default maker rebate / taker fee (docs/OPTIONS-EXCHANGE.md §7).
    n += sqlx::query(
        "INSERT INTO group_settings (tenant, group_code, symbol, maker_fee_per_contract, taker_fee_per_contract) VALUES ('kalks', '*', '*', $1, $2) ON CONFLICT DO NOTHING",
    )
    .bind(crate::model::DEFAULT_MAKER_FEE)
    .bind(crate::model::DEFAULT_TAKER_FEE)
    .execute(&mut *tx)
    .await?
    .rows_affected();

    let dir = Path::new(holidays_dir);
    match std::fs::read_dir(dir) {
        Ok(entries) => {
            let mut files: Vec<_> = entries.filter_map(|e| e.ok().map(|e| e.path())).filter(|p| p.extension().is_some_and(|x| x == "json")).collect();
            files.sort();
            for path in files {
                let f: HolidayFile = match std::fs::read_to_string(&path).map_err(anyhow::Error::from).and_then(|s| Ok(serde_json::from_str(&s)?)) {
                    Ok(f) => f,
                    Err(e) => {
                        tracing::warn!(file = %path.display(), error = %e, "holiday seed file skipped");
                        continue;
                    }
                };
                for h in f.holidays {
                    n += sqlx::query("INSERT INTO holidays (calendar, day, name) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING")
                        .bind(&f.calendar)
                        .bind(h.date)
                        .bind(&h.name)
                        .execute(&mut *tx)
                        .await?
                        .rows_affected();
                }
            }
        }
        Err(e) => tracing::warn!(dir = %dir.display(), error = %e, "holiday seed directory not readable; calendars stay as stored"),
    }
    if n > 0 {
        store::bump(&mut tx).await?;
        store::audit(&mut tx, "kalks", "seed", "seed", "", None, Some(json!({"rows": n})), "first-start seed").await?;
    }
    tx.commit().await?;
    Ok(n)
}
