//! Instrument contract specifications and trading sessions.
//!
//! Built from two files: `config/instruments.json` (the market-data catalogue: symbol, asset class, digits,
//! session filter) and `config/trading-specs.json` (contract size, lots, margin, swaps, sessions). Session
//! and server-time rules are the same as market-data's (crate `markethours`): server time is GMT+3 while US DST
//! is active and GMT+2 otherwise (New York close = 00:00 server time).
//!
//! **Core and catalogue instruments.** The 28 hand-maintained core instruments take their specs from `classes`
//! (per asset class) and `symbols` (per symbol) exactly as before. The provider catalogue (rows with
//! `"tier": "catalogue"`, generated by `scripts/gen-catalogue.mjs`) takes them from conservative per-class
//! `templates` instead (the row's `template`, else its asset class), which the Back Office may override field by
//! field (`Overrides::templates`, table `symbol_templates`). A catalogue row also brings its own session,
//! holiday calendar (`config/holidays`, `config/holidays/exchanges`) and base / quote currency.
//!
//! **Live switch.** Every instrument trades on demo accounts. On live accounts: core instruments always; a
//! catalogue instrument when, in this order, its Back Office symbol switch says so (table `symbol_live`), else not
//! when its row is kept off live trading (`"live_off": "<reason>"`), else its Back Office asset-class switch, else
//! its row's default (`"live": true` for forex, metals, energies, indices and crypto; absent = off, e.g. stocks).
//!
//! **Swaps** are points per lot per night (`swap_mode` "points", the core instruments) or an annual percentage of
//! the position's value (`swap_mode` "percent": rate / 100 / 360 per night, / 365 for instruments charged every
//! night), negative = the client pays.

use chrono::{DateTime, Datelike, Duration, NaiveDate, TimeZone, Utc, Weekday};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::{BTreeMap, HashMap};
use std::str::FromStr;
use std::sync::{Arc, RwLock};

pub use markethours::{Holidays, Session};

use crate::money::{D, HUNDRED, ZERO, from_f64, rdp};

#[derive(Clone, Debug)]
pub struct Spec {
    pub symbol: String,
    pub asset_class: String,
    pub digits: u32,
    pub point: D,
    pub pip_size: D,
    pub contract_size: D,
    /// Profit currency (P&L is computed in it, then converted to USD).
    pub quote_ccy: String,
    pub lot_min: D,
    pub lot_max: D,
    pub lot_step: D,
    /// 100 = margin is notional / leverage.
    pub margin_pct: D,
    /// Cap on the account leverage for this symbol.
    pub max_leverage: u32,
    /// Points per lot per night (negative = the client pays).
    pub swap_long: D,
    pub swap_short: D,
    pub triple_swap_day: Option<Weekday>,
    /// Swaps are charged every night (crypto) instead of Monday–Friday nights only.
    pub swap_all_days: bool,
    /// How `swap_long` / `swap_short` are expressed.
    pub swap_mode: SwapMode,
    pub session: Session,
    /// Holiday calendar closing the session (catalogue instruments; None for the core instruments).
    pub holidays: Option<Arc<Holidays>>,
    pub stops_level_points: i64,
    /// Round-turn commission per lot overriding the group value.
    pub commission_per_lot: Option<D>,
    /// One of the hand-maintained core instruments (not from the provider catalogue).
    pub core: bool,
    /// Display name (catalogue instruments; empty for the core ones).
    pub name: String,
    /// Base currency when the instrument has one (FX pairs, crypto).
    pub base_ccy: Option<String>,
    /// Template the specs came from (catalogue instruments).
    pub template: Option<String>,
    /// Tradable on live accounts (see the module docs). Demo accounts trade every instrument.
    pub live: bool,
    /// Why a catalogue instrument is kept off live trading by default (config row `live_off`).
    pub live_off: Option<String>,
    /// Its row's default before any Back Office switch (`"live": true`); always true for core instruments.
    pub live_default: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SwapMode {
    /// Points per lot per night.
    Points,
    /// Annual percentage of the position's value.
    PercentYear,
}

impl SwapMode {
    pub fn parse(s: &str) -> Option<SwapMode> {
        match s {
            "points" => Some(SwapMode::Points),
            "percent" => Some(SwapMode::PercentYear),
            _ => None,
        }
    }
    pub fn as_str(self) -> &'static str {
        match self {
            SwapMode::Points => "points",
            SwapMode::PercentYear => "percent",
        }
    }
}

impl Spec {
    pub fn round_price(&self, p: D) -> D {
        rdp(p, self.digits)
    }

    /// Validates a lot size against min / max / step.
    pub fn volume_error(&self, v: D) -> Option<String> {
        if v <= ZERO {
            return Some("Enter a volume above 0".into());
        }
        if v < self.lot_min {
            return Some(format!("Minimum volume for {} is {} lots", self.symbol, self.lot_min.normalize()));
        }
        if v > self.lot_max {
            return Some(format!("Maximum volume for {} is {} lots", self.symbol, self.lot_max.normalize()));
        }
        if !(v % self.lot_step).is_zero() {
            return Some(format!("Volume step for {} is {} lots", self.symbol, self.lot_step.normalize()));
        }
        None
    }

    /// Is the market open for trading at `ts` (same rules as market-data's session filter).
    pub fn is_open(&self, ts: DateTime<Utc>) -> bool {
        self.session.is_open(ts, self.holidays.as_deref())
    }

    /// Swap of `volume` lots on `side` for one night at `price`, in the profit currency (before the night multiplier).
    pub fn swap_per_night(&self, buy: bool, volume: D, price: D) -> D {
        let rate = if buy { self.swap_long } else { self.swap_short };
        match self.swap_mode {
            SwapMode::Points => rate * self.point * self.contract_size * volume,
            SwapMode::PercentYear => {
                let days = D::from(if self.swap_all_days { 365 } else { 360 });
                rate / HUNDRED / days * self.contract_size * volume * price
            }
        }
    }

    /// Nights on which a swap is charged: the server day that just ended (`day`).
    /// Returns the multiplier (0 = no swap that night, 3 = triple).
    pub fn swap_multiplier(&self, day: NaiveDate) -> i64 {
        let wd = day.weekday();
        if !self.swap_all_days && matches!(wd, Weekday::Sat | Weekday::Sun) {
            return 0;
        }
        if self.triple_swap_day == Some(wd) { 3 } else { 1 }
    }
}

/// One spec layer as written in `config/trading-specs.json` (`classes`, `templates`, `symbols`) or stored as a
/// Back Office template override: every field optional, the more specific layer wins.
#[derive(Deserialize, Serialize, Clone, Default, Debug, PartialEq)]
pub struct RawSpec {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contract_size: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lot_min: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lot_max: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lot_step: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub margin_pct: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_leverage: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub swap_long: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub swap_short: Option<f64>,
    #[serde(default, deserialize_with = "de_opt_opt", skip_serializing_if = "Option::is_none")]
    pub triple_swap_day: Option<Option<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub swap_days: Option<String>,
    /// "points" (default) or "percent" (annual % of the position value)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub swap_mode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stops_level_points: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub commission_per_lot: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quote_ccy: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pip_size: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_ccy: Option<String>,
    /// Template documentation (ignored by the engine).
    #[serde(default, rename = "_comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
}

fn de_opt_opt<'de, De: serde::Deserializer<'de>>(d: De) -> Result<Option<Option<String>>, De::Error> {
    Ok(Some(Option::<String>::deserialize(d)?))
}

impl RawSpec {
    /// `over`'s fields replace this layer's.
    pub fn merged(&self, over: &RawSpec) -> RawSpec {
        macro_rules! m {
            ($($f:ident),*) => { RawSpec { $($f: over.$f.clone().or(self.$f.clone()),)* } };
        }
        m!(contract_size, lot_min, lot_max, lot_step, margin_pct, max_leverage, swap_long, swap_short, triple_swap_day, swap_days, swap_mode, session, stops_level_points, commission_per_lot, quote_ccy, pip_size, base_ccy, comment)
    }

    /// Checks a template (after the Back Office override is applied): conservative bounds, so a typo can never make
    /// a contract free to trade or impossible to close.
    pub fn validate_template(&self) -> Result<(), (&'static str, String)> {
        let pos = |f: &'static str, v: Option<f64>| match v {
            Some(x) if x.is_finite() && x > 0.0 => Ok(x),
            Some(_) => Err((f, format!("{f} must be above 0"))),
            None => Err((f, format!("{f} is required"))),
        };
        let cs = pos("contract_size", self.contract_size)?;
        let min = pos("lot_min", self.lot_min)?;
        let max = pos("lot_max", self.lot_max)?;
        let step = pos("lot_step", self.lot_step)?;
        let margin = pos("margin_pct", self.margin_pct)?;
        if cs > 1e9 {
            return Err(("contract_size", "contract_size is at most 1,000,000,000".into()));
        }
        if min > max {
            return Err(("lot_min", "lot_min must not exceed lot_max".into()));
        }
        if max > 1e6 {
            return Err(("lot_max", "lot_max is at most 1,000,000".into()));
        }
        let ratio = min / step;
        if (ratio - ratio.round()).abs() > 1e-9 {
            return Err(("lot_step", "lot_min must be a whole number of lot_step".into()));
        }
        if !(1.0..=10_000.0).contains(&margin) {
            return Err(("margin_pct", "margin_pct must be 1–10,000 (100 = notional / leverage)".into()));
        }
        match self.max_leverage {
            Some(l) if (1..=1000).contains(&l) => {}
            Some(_) => return Err(("max_leverage", "max_leverage must be 1–1000".into())),
            None => return Err(("max_leverage", "max_leverage is required".into())),
        }
        for (f, v) in [("swap_long", self.swap_long), ("swap_short", self.swap_short), ("commission_per_lot", self.commission_per_lot)] {
            if v.is_some_and(|x| !x.is_finite() || x.abs() > 1e7) {
                return Err((f, format!("{f} is out of range")));
            }
        }
        if self.commission_per_lot.is_some_and(|c| c < 0.0) {
            return Err(("commission_per_lot", "commission_per_lot must not be negative".into()));
        }
        if let Some(Some(d)) = &self.triple_swap_day
            && Weekday::from_str(d).is_err()
        {
            return Err(("triple_swap_day", format!("unknown weekday {d}")));
        }
        if self.swap_days.as_deref().is_some_and(|d| d != "mon-fri" && d != "all") {
            return Err(("swap_days", "swap_days must be mon-fri or all".into()));
        }
        match self.swap_mode.as_deref().map(SwapMode::parse) {
            Some(None) => return Err(("swap_mode", "swap_mode must be points or percent".into())),
            Some(Some(SwapMode::PercentYear)) => {
                for (f, v) in [("swap_long", self.swap_long), ("swap_short", self.swap_short)] {
                    if v.is_some_and(|x| x.abs() > 100.0) {
                        return Err((f, format!("{f} is a yearly percentage: -100 to 100")));
                    }
                }
            }
            _ => {}
        }
        match self.session.as_deref() {
            Some(s) if Session::parse(s).is_some() => {}
            Some(s) => return Err(("session", format!("unknown session {s}"))),
            None => return Err(("session", "session is required".into())),
        }
        if self.stops_level_points.is_some_and(|p| !(0..=1_000_000).contains(&p)) {
            return Err(("stops_level_points", "stops_level_points must be 0–1,000,000".into()));
        }
        Ok(())
    }
}

#[derive(Deserialize, Clone, Debug)]
struct RawFile {
    classes: HashMap<String, RawSpec>,
    #[serde(default)]
    templates: BTreeMap<String, RawSpec>,
    symbols: HashMap<String, RawSpec>,
}

#[derive(Deserialize, Clone, Debug)]
struct RawInstrument {
    symbol: String,
    asset_class: String,
    digits: u32,
    #[serde(default)]
    session: Option<String>,
    #[serde(default)]
    tier: Option<String>,
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    template: Option<String>,
    #[serde(default)]
    calendar: Option<String>,
    #[serde(default)]
    base_ccy: Option<String>,
    #[serde(default)]
    quote_ccy: Option<String>,
    #[serde(default)]
    pip_size: Option<f64>,
    #[serde(default)]
    contract_size: Option<f64>,
    /// Live trading by default (catalogue rows of forex, metals, energies, indices, crypto).
    #[serde(default)]
    live: Option<bool>,
    /// Kept off live trading by default, with the reason.
    #[serde(default)]
    live_off: Option<String>,
}

impl RawInstrument {
    fn core(&self) -> bool {
        self.tier.as_deref() != Some("catalogue")
    }
    fn template_key(&self) -> String {
        self.template.clone().unwrap_or_else(|| self.asset_class.clone())
    }
}

fn weekday(s: &str) -> Option<Weekday> {
    Weekday::from_str(s).ok()
}

/// What the Back Office changed on top of the files: template fields and the live-trading switch.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Overrides {
    /// template key → fields replacing the file template's
    pub templates: BTreeMap<String, RawSpec>,
    /// asset-class switch (true = live on, false = live off); absent = the rows' own default
    pub live_classes: BTreeMap<String, bool>,
    /// per-symbol switch, wins over everything (true = live on, false = live off)
    pub live_symbols: BTreeMap<String, bool>,
}

impl Overrides {
    /// Is live trading on for a catalogue instrument? `default` = its row's `live`, `kept_off` = its row's
    /// `live_off` (an asset-class switch does not turn such a symbol on; only its own switch does).
    pub fn live(&self, symbol: &str, asset_class: &str, default: bool, kept_off: bool) -> bool {
        if let Some(on) = self.live_symbols.get(symbol) {
            return *on;
        }
        if kept_off {
            return false;
        }
        self.live_classes.get(asset_class).copied().unwrap_or(default)
    }
}

/// The parsed files, kept so the specs can be rebuilt when the Back Office changes a template or the live switch.
#[derive(Debug)]
pub struct SpecSource {
    list: Vec<RawInstrument>,
    file: RawFile,
    calendars: HashMap<String, Arc<Holidays>>,
}

impl SpecSource {
    pub fn parse(instruments_json: &str, specs_json: &str, holidays_dir: &str) -> anyhow::Result<Self> {
        let list: Vec<RawInstrument> = serde_json::from_str(instruments_json)?;
        let file: RawFile = serde_json::from_str(specs_json)?;
        let calendars = Holidays::load_dir(holidays_dir).map_err(|e| anyhow::anyhow!("holiday calendars: {e}"))?.into_iter().map(|(k, v)| (k, Arc::new(v))).collect();
        Ok(Self { list, file, calendars })
    }

    /// The file template for `key` (before Back Office overrides).
    pub fn template(&self, key: &str) -> Option<&RawSpec> {
        self.file.templates.get(key)
    }

    pub fn template_keys(&self) -> Vec<String> {
        self.file.templates.keys().cloned().collect()
    }

    /// Catalogue symbols using template `key`.
    pub fn template_symbols(&self, key: &str) -> Vec<String> {
        self.list.iter().filter(|i| !i.core() && i.template_key() == key).map(|i| i.symbol.clone()).collect()
    }

    /// Every instrument with its specs, the Back Office overrides applied.
    pub fn build(&self, ov: &Overrides) -> anyhow::Result<BTreeMap<String, Spec>> {
        let mut map = BTreeMap::new();
        let empty = RawSpec::default();
        for i in &self.list {
            let core = i.core();
            if map.contains_key(&i.symbol) {
                anyhow::bail!("{}: listed twice in the instrument catalogue", i.symbol);
            }
            // core: symbol over class; catalogue: symbol over its template (file + Back Office override)
            let base = if core {
                self.file.classes.get(&i.asset_class).cloned().unwrap_or_default()
            } else {
                let key = i.template_key();
                let t = self.file.templates.get(&key).ok_or_else(|| anyhow::anyhow!("{}: no template {key} in trading-specs.json", i.symbol))?;
                t.merged(ov.templates.get(&key).unwrap_or(&empty))
            };
            let mut sym = self.file.symbols.get(&i.symbol).cloned().unwrap_or_default();
            if !core {
                // the catalogue row's own currencies and pip size sit between the symbol overrides and the template
                sym = RawSpec { quote_ccy: i.quote_ccy.clone(), base_ccy: i.base_ccy.clone(), pip_size: i.pip_size, contract_size: i.contract_size, ..Default::default() }.merged(&sym);
            }
            let class = base;
            macro_rules! pick {
                ($f:ident, $d:expr) => {
                    sym.$f.clone().or(class.$f.clone()).unwrap_or($d)
                };
            }
            let dec = |f: f64, what: &str| from_f64(f).ok_or_else(|| anyhow::anyhow!("{}: invalid {what}", i.symbol));
            let point = D::new(1, i.digits);
            let triple = match sym.triple_swap_day.clone().or(class.triple_swap_day.clone()) {
                Some(Some(d)) => Some(weekday(&d).ok_or_else(|| anyhow::anyhow!("{}: bad triple_swap_day {d}", i.symbol))?),
                _ => None,
            };
            let (session, holidays) = if core {
                // exactly the original rules
                let s = match (i.session.as_deref(), pick!(session, String::new()).as_str()) {
                    (Some("us_equity"), _) | (_, "us_equity") => Session::parse("us_equity").unwrap(),
                    (_, "24x7") => Session::Always,
                    (_, "fx") => Session::Fx,
                    _ if i.asset_class == "crypto" => Session::Always,
                    _ => Session::Fx,
                };
                (s, None)
            } else {
                let name = i.session.clone().or(pick!(session, String::new()).into()).filter(|s| !s.is_empty()).unwrap_or_else(|| "fx".into());
                let s = Session::parse(&name).ok_or_else(|| anyhow::anyhow!("{}: unknown session {name}", i.symbol))?;
                let h = match &i.calendar {
                    Some(c) => Some(self.calendars.get(c).cloned().ok_or_else(|| anyhow::anyhow!("{}: holiday calendar {c} not found", i.symbol))?),
                    None => None,
                };
                (s, h)
            };
            let spec = Spec {
                symbol: i.symbol.clone(),
                asset_class: i.asset_class.clone(),
                digits: i.digits,
                point,
                pip_size: dec(pick!(pip_size, 0.0), "pip_size").map(|p| if p.is_zero() { point } else { p })?,
                contract_size: dec(pick!(contract_size, 1.0), "contract_size")?,
                quote_ccy: pick!(quote_ccy, "USD".to_string()),
                lot_min: dec(pick!(lot_min, 0.01), "lot_min")?,
                lot_max: dec(pick!(lot_max, 100.0), "lot_max")?,
                lot_step: dec(pick!(lot_step, 0.01), "lot_step")?,
                margin_pct: dec(pick!(margin_pct, 100.0), "margin_pct")?,
                max_leverage: pick!(max_leverage, 1000),
                swap_long: dec(pick!(swap_long, 0.0), "swap_long")?,
                swap_short: dec(pick!(swap_short, 0.0), "swap_short")?,
                triple_swap_day: triple,
                swap_all_days: pick!(swap_days, "mon-fri".to_string()) == "all",
                swap_mode: SwapMode::parse(&pick!(swap_mode, "points".to_string())).ok_or_else(|| anyhow::anyhow!("{}: swap_mode must be points or percent", i.symbol))?,
                session,
                holidays,
                stops_level_points: pick!(stops_level_points, 0),
                commission_per_lot: sym.commission_per_lot.or(class.commission_per_lot).map(|c| dec(c, "commission_per_lot")).transpose()?,
                core,
                name: i.name.clone().unwrap_or_default(),
                base_ccy: if core { sym.base_ccy.clone() } else { pick!(base_ccy, String::new()).into() }.filter(|s: &String| !s.is_empty()),
                template: (!core).then(|| i.template_key()),
                live: core || ov.live(&i.symbol, &i.asset_class, i.live == Some(true), i.live_off.is_some()),
                live_off: if core { None } else { i.live_off.clone() },
                live_default: core || (i.live == Some(true) && i.live_off.is_none()),
            };
            if spec.lot_step <= ZERO || spec.lot_min <= ZERO || spec.contract_size <= ZERO || spec.margin_pct <= ZERO {
                anyhow::bail!("{}: lot_step, lot_min, contract_size and margin_pct must be > 0", spec.symbol);
            }
            map.insert(i.symbol.clone(), spec);
        }
        Ok(map)
    }
}

/// All tradable symbols (ordered by name).
#[derive(Clone, Debug, Default)]
pub struct Specs {
    map: BTreeMap<String, Spec>,
    source: Option<Arc<SpecSource>>,
    overrides: Overrides,
}

impl Specs {
    /// `holidays` are read from the `holidays` directory next to the specs file (config/holidays).
    pub fn load(instruments_file: &str, specs_file: &str) -> anyhow::Result<Self> {
        let inst = std::fs::read_to_string(instruments_file).map_err(|e| anyhow::anyhow!("reading {instruments_file}: {e}"))?;
        let specs = std::fs::read_to_string(specs_file).map_err(|e| anyhow::anyhow!("reading {specs_file}: {e}"))?;
        let dir = std::path::Path::new(specs_file).parent().map(|p| p.join("holidays")).unwrap_or_else(|| "holidays".into());
        Self::from_source(SpecSource::parse(&inst, &specs, &dir.to_string_lossy())?, Overrides::default())
    }

    /// Parses the files with the repo's holiday calendars (config/holidays).
    pub fn parse(instruments_json: &str, specs_json: &str) -> anyhow::Result<Self> {
        Self::from_source(SpecSource::parse(instruments_json, specs_json, concat!(env!("CARGO_MANIFEST_DIR"), "/../../config/holidays"))?, Overrides::default())
    }

    pub fn from_source(src: SpecSource, ov: Overrides) -> anyhow::Result<Self> {
        let map = src.build(&ov)?;
        Ok(Self { map, source: Some(Arc::new(src)), overrides: ov })
    }

    /// The same files with other Back Office overrides.
    pub fn with_overrides(&self, ov: Overrides) -> anyhow::Result<Self> {
        let src = self.source.clone().ok_or_else(|| anyhow::anyhow!("specs were not built from files"))?;
        let map = src.build(&ov)?;
        Ok(Self { map, source: Some(src), overrides: ov })
    }

    pub fn source(&self) -> Option<&SpecSource> {
        self.source.as_deref()
    }

    pub fn overrides(&self) -> &Overrides {
        &self.overrides
    }

    pub fn get(&self, symbol: &str) -> Option<&Spec> {
        self.map.get(symbol)
    }

    pub fn all(&self) -> impl Iterator<Item = &Spec> {
        self.map.values()
    }

    pub fn symbols(&self) -> Vec<String> {
        self.map.keys().cloned().collect()
    }

    pub fn len(&self) -> usize {
        self.map.len()
    }

    pub fn is_empty(&self) -> bool {
        self.map.is_empty()
    }

    /// The symbol that converts `ccy` to USD and whether its price multiplies (`EURUSD`) or divides (`USDJPY`).
    /// Core instruments are preferred, so currencies the core instruments already convert keep the same pair
    /// whatever the catalogue adds.
    pub fn usd_pair(&self, ccy: &str) -> Option<(String, bool)> {
        for core in [true, false] {
            let direct = format!("{ccy}USD");
            if self.map.get(&direct).is_some_and(|s| s.core == core) {
                return Some((direct, true));
            }
            let inverse = format!("USD{ccy}");
            if self.map.get(&inverse).is_some_and(|s| s.core == core) {
                return Some((inverse, false));
            }
        }
        None
    }
}

/// The engine's current specs. Replaced as a whole when the Back Office changes a template or the live switch;
/// readers take a snapshot (`load`) for the duration of one operation.
pub struct SpecsCell(RwLock<Arc<Specs>>);

impl SpecsCell {
    pub fn new(specs: Arc<Specs>) -> Self {
        Self(RwLock::new(specs))
    }
    pub fn load(&self) -> Arc<Specs> {
        self.0.read().unwrap().clone()
    }
    pub fn store(&self, specs: Specs) {
        *self.0.write().unwrap() = Arc::new(specs);
    }
}

impl From<Arc<Specs>> for SpecsCell {
    fn from(s: Arc<Specs>) -> Self {
        Self::new(s)
    }
}

/// Helper for JSON APIs: a spec layer as JSON (only the set fields).
pub fn raw_json(r: &RawSpec) -> Value {
    serde_json::to_value(r).unwrap_or(Value::Null)
}

pub fn pct(v: D) -> D {
    v / HUNDRED
}

/* ------------------------------------------------------------------ */
/* Server time (NY close)                                              */
/* ------------------------------------------------------------------ */

fn midnight(d: NaiveDate) -> DateTime<Utc> {
    Utc.from_utc_datetime(&d.and_hms_opt(0, 0, 0).unwrap())
}

fn nth_weekday(year: i32, month: u32, weekday: Weekday, n: u32) -> NaiveDate {
    let first = NaiveDate::from_ymd_opt(year, month, 1).unwrap();
    let shift = (7 + weekday.num_days_from_sunday() as i64 - first.weekday().num_days_from_sunday() as i64) % 7;
    first + Duration::days(shift + 7 * (n as i64 - 1))
}

/// Server-time offset (seconds east of UTC): +3h during US DST, +2h otherwise (same as market-data).
/// US DST: second Sunday of March 07:00 UTC → first Sunday of November 06:00 UTC.
pub fn server_offset_secs(ts: DateTime<Utc>) -> i64 {
    let y = ts.year();
    let start = midnight(nth_weekday(y, 3, Weekday::Sun, 2)) + Duration::hours(7);
    let end = midnight(nth_weekday(y, 11, Weekday::Sun, 1)) + Duration::hours(6);
    if ts >= start && ts < end { 3 * 3600 } else { 2 * 3600 }
}

/// Server-time calendar date of `ts`.
pub fn server_date(ts: DateTime<Utc>) -> NaiveDate {
    (ts + Duration::seconds(server_offset_secs(ts))).date_naive()
}

/// The UTC instant of 00:00 server time on `day` (the rollover that ends `day - 1`).
pub fn server_midnight(day: NaiveDate) -> DateTime<Utc> {
    let local = midnight(day);
    // offset at the rollover instant; DST switches happen on Sunday mornings, never at midnight,
    // so one correction step is exact
    let guess = local - Duration::seconds(server_offset_secs(local - Duration::hours(2)));
    local - Duration::seconds(server_offset_secs(guess))
}

/// The first rollover strictly after `ts`, with the server day it closes.
pub fn next_rollover(ts: DateTime<Utc>) -> (DateTime<Utc>, NaiveDate) {
    let today = server_date(ts);
    let tomorrow = today.succ_opt().unwrap();
    (server_midnight(tomorrow), today)
}

/// End of the current server day (expiry of "Today" orders).
pub fn end_of_server_day(ts: DateTime<Utc>) -> DateTime<Utc> {
    next_rollover(ts).0
}

#[cfg(test)]
mod tests {
    use super::*;

    fn t(s: &str) -> DateTime<Utc> {
        DateTime::parse_from_rfc3339(s).unwrap().with_timezone(&Utc)
    }

    pub fn test_specs() -> Specs {
        let inst = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/../../config/instruments.json")).unwrap();
        let specs = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/../../config/trading-specs.json")).unwrap();
        Specs::parse(&inst, &specs).unwrap()
    }

    #[test]
    fn loads_repo_specs() {
        let s = test_specs();
        let eu = s.get("EURUSD").unwrap();
        assert_eq!(eu.contract_size, D::from(100000));
        assert_eq!(eu.triple_swap_day, Some(Weekday::Wed));
        assert_eq!(eu.session, Session::Fx);
        let btc = s.get("BTCUSD").unwrap();
        assert_eq!(btc.session, Session::Always);
        assert!(btc.swap_all_days);
        assert_eq!(s.get("AAPL").unwrap().session, Session::parse("us_equity").unwrap());
        assert_eq!(s.get("XAGUSD").unwrap().contract_size, D::from(5000));
        assert_eq!(s.usd_pair("JPY"), Some(("USDJPY".into(), false)));
        assert_eq!(s.usd_pair("EUR"), Some(("EURUSD".into(), true)));
    }

    #[test]
    fn volume_steps() {
        let s = test_specs();
        let eu = s.get("EURUSD").unwrap();
        assert!(eu.volume_error(D::from_str("0.01").unwrap()).is_none());
        assert!(eu.volume_error(D::from_str("0.015").unwrap()).is_some());
        assert!(eu.volume_error(D::from_str("0.001").unwrap()).is_some());
        assert!(eu.volume_error(D::from(101)).is_some());
        let idx = s.get("US30").unwrap();
        assert!(idx.volume_error(D::from_str("0.1").unwrap()).is_none());
        assert!(idx.volume_error(D::from_str("0.15").unwrap()).is_some());
    }

    #[test]
    fn sessions_match_market_data() {
        let s = test_specs();
        let fx = s.get("EURUSD").unwrap();
        assert!(fx.is_open(t("2026-09-25T20:59:59Z")));
        assert!(!fx.is_open(t("2026-09-25T21:00:00Z")));
        assert!(!fx.is_open(t("2026-09-27T20:59:00Z")));
        assert!(fx.is_open(t("2026-09-27T21:00:00Z")));
        assert!(!fx.is_open(t("2026-01-11T21:30:00Z")));
        assert!(fx.is_open(t("2026-01-11T22:00:00Z")));
        assert!(s.get("BTCUSD").unwrap().is_open(t("2026-09-26T09:00:00Z")));
        let aapl = s.get("AAPL").unwrap();
        assert!(!aapl.is_open(t("2026-09-24T13:29:59Z")));
        assert!(aapl.is_open(t("2026-09-24T13:30:00Z")));
        assert!(!aapl.is_open(t("2026-09-24T20:00:00Z")));
        assert!(!aapl.is_open(t("2026-09-26T15:00:00Z")));
    }

    #[test]
    fn rollover_instants_follow_dst() {
        // September: GMT+3 → 00:00 server = 21:00 UTC
        assert_eq!(server_midnight(NaiveDate::from_ymd_opt(2026, 9, 25).unwrap()), t("2026-09-24T21:00:00Z"));
        // January: GMT+2 → 22:00 UTC
        assert_eq!(server_midnight(NaiveDate::from_ymd_opt(2026, 1, 15).unwrap()), t("2026-01-14T22:00:00Z"));
        // DST starts Sunday 2026-03-08 07:00 UTC. Sunday 00:00 server is still GMT+2, Monday 00:00 is GMT+3.
        assert_eq!(server_midnight(NaiveDate::from_ymd_opt(2026, 3, 8).unwrap()), t("2026-03-07T22:00:00Z"));
        assert_eq!(server_midnight(NaiveDate::from_ymd_opt(2026, 3, 9).unwrap()), t("2026-03-08T21:00:00Z"));
        // DST ends Sunday 2026-11-01 06:00 UTC.
        assert_eq!(server_midnight(NaiveDate::from_ymd_opt(2026, 11, 1).unwrap()), t("2026-10-31T21:00:00Z"));
        assert_eq!(server_midnight(NaiveDate::from_ymd_opt(2026, 11, 2).unwrap()), t("2026-11-01T22:00:00Z"));
        // next rollover after Sunday evening 2026-03-08 20:00 UTC (server Sunday 23:00) is 21:00 UTC
        let (at, day) = next_rollover(t("2026-03-08T20:00:00Z"));
        assert_eq!(at, t("2026-03-08T21:00:00Z"));
        assert_eq!(day, NaiveDate::from_ymd_opt(2026, 3, 8).unwrap());
        // server date flips exactly at the rollover
        assert_eq!(server_date(t("2026-09-24T20:59:59Z")), NaiveDate::from_ymd_opt(2026, 9, 24).unwrap());
        assert_eq!(server_date(t("2026-09-24T21:00:00Z")), NaiveDate::from_ymd_opt(2026, 9, 25).unwrap());
    }

    #[test]
    fn swap_nights() {
        let s = test_specs();
        let fx = s.get("EURUSD").unwrap();
        let d = |y, m, dd| NaiveDate::from_ymd_opt(y, m, dd).unwrap();
        assert_eq!(fx.swap_multiplier(d(2026, 9, 21)), 1); // Monday night
        assert_eq!(fx.swap_multiplier(d(2026, 9, 23)), 3); // Wednesday night: triple
        assert_eq!(fx.swap_multiplier(d(2026, 9, 26)), 0); // Saturday: closed
        let btc = s.get("BTCUSD").unwrap();
        assert_eq!(btc.swap_multiplier(d(2026, 9, 26)), 1);
        assert_eq!(btc.swap_multiplier(d(2026, 9, 23)), 1);
        let idx = s.get("US30").unwrap();
        assert_eq!(idx.swap_multiplier(d(2026, 9, 25)), 3); // Friday triple for indices
    }
}

#[cfg(test)]
pub use tests::test_specs;
