// Generates src/i18n/loaders.generated.ts: one lazy import per (language, namespace) the app uses, so a phone only
// loads the reader's language and only the namespaces the app needs (not the whole web catalog).
// Namespaces: BASE below + every catalog namespace whose name starts with "mobile". Re-run after adding one:
//   pnpm --filter @kalks/mobile i18n
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const catalog = join(here, "..", "..", "..", "packages", "i18n", "src", "catalog");
const BASE = ["common", "auth", "market", "order", "portfolio", "wallet", "dashboard", "security", "kyc", "news", "support", "profile"];

const en = readdirSync(join(catalog, "en")).filter((f) => f.endsWith(".ts") && f !== "index.ts").map((f) => f.slice(0, -3));
const namespaces = [...new Set([...BASE, ...en.filter((n) => n.startsWith("mobile"))])].filter((n) => en.includes(n)).sort();
const locales = readdirSync(catalog).filter((d) => d !== "en" && existsSync(join(catalog, d, "index.ts"))).sort();

let out = "// Generated by scripts/gen-i18n.mjs. Do not edit by hand.\n";
out += "/* eslint-disable */\n";
out += "type Loader = () => Promise<{ default: unknown }>;\n\n";
out += `export const NAMESPACES = ${JSON.stringify(namespaces)} as const;\n\n`;
out += "export const LOADERS: Record<string, Record<string, Loader>> = {\n";
for (const l of locales) {
  const entries = namespaces.filter((n) => existsSync(join(catalog, l, `${n}.ts`)));
  out += `  ${JSON.stringify(l)}: {\n`;
  for (const n of entries) out += `    ${JSON.stringify(n)}: () => import("@kalks/i18n/catalog/${l}/${n}"),\n`;
  out += "  },\n";
}
out += "};\n";
writeFileSync(join(here, "..", "src", "i18n", "loaders.generated.ts"), out);
console.log(`i18n loaders: ${locales.length} languages x ${namespaces.length} namespaces`);
