// Chart indicators on the phone (web: lib/indicators.ts + components/chart/indicators/state.ts). The maths runs in the
// chart page (assets/chart/indicators.bundle.js, built from the web code); the app keeps only the list of instances per
// symbol and reads the registry (names, categories, params, outputs, levels) from assets/chart/indicators.json for its
// menus. Both files are generated by tool/build_chart_indicators.mjs.
import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// One input of an indicator (web ParamDef): int / float with a range, a price source, or a choice.
@immutable
class IndParam {
  const IndParam({
    required this.key,
    required this.label,
    required this.kind,
    required this.def,
    this.min = 0,
    this.max = 0,
    this.step = 1,
    this.options = const [],
  });

  factory IndParam.fromJson(Map<String, dynamic> j) => IndParam(
    key: '${j['key']}',
    label: '${j['label']}',
    kind: '${j['kind']}',
    def: j['def'] as Object,
    min: (j['min'] as num?)?.toDouble() ?? 0,
    max: (j['max'] as num?)?.toDouble() ?? 0,
    step: (j['step'] as num?)?.toDouble() ?? 1,
    options: [
      for (final o in (j['options'] as List? ?? const []))
        if (o is Map) (value: '${o['value']}', label: '${o['label']}'),
    ],
  );

  final String key, label;

  /// int | float | source | select
  final String kind;
  final Object def;
  final double min, max, step;
  final List<({String value, String label})> options;

  bool get numeric => kind == 'int' || kind == 'float';
}

/// One plotted output (web OutputDef).
@immutable
class IndOutput {
  const IndOutput({required this.key, required this.label, required this.kind, required this.color, this.width, this.histColor});

  factory IndOutput.fromJson(Map<String, dynamic> j) => IndOutput(
    key: '${j['key']}',
    label: '${j['label']}',
    kind: '${j['kind']}',
    color: '${j['color']}',
    width: (j['width'] as num?)?.toInt(),
    histColor: j['histColor'] as String?,
  );

  final String key, label;

  /// line | hist | dots | markers
  final String kind;

  /// A colour token (ember, gold, up, down, warn, info, fg2, fg3) or a CSS colour.
  final String color;
  final int? width;
  final String? histColor;
}

/// One indicator of the registry (web IndicatorDef, without the kernels).
@immutable
class IndDef {
  const IndDef({
    required this.type,
    required this.name,
    required this.short,
    required this.category,
    required this.pane,
    required this.description,
    required this.params,
    required this.outputs,
    required this.levels,
  });

  factory IndDef.fromJson(Map<String, dynamic> j) => IndDef(
    type: '${j['type']}',
    name: '${j['name']}',
    short: '${j['short']}',
    category: '${j['category']}',
    pane: '${j['pane']}',
    description: '${j['description'] ?? ''}',
    params: [for (final p in (j['params'] as List? ?? const [])) IndParam.fromJson((p as Map).cast<String, dynamic>())],
    outputs: [for (final o in (j['outputs'] as List? ?? const [])) IndOutput.fromJson((o as Map).cast<String, dynamic>())],
    levels: [for (final l in (j['levels'] as List? ?? const [])) (l as num).toDouble()],
  );

  final String type, name, short, category;

  /// overlay | separate (a sub-window)
  final String pane;
  final String description;
  final List<IndParam> params;
  final List<IndOutput> outputs;

  /// Default horizontal levels of a sub-window (RSI 70 / 30 …).
  final List<double> levels;

  bool get separate => pane == 'separate';
}

/// The indicator registry (35 indicators, web order) and the colour tokens / sources of the settings.
@immutable
class IndRegistry {
  const IndRegistry({required this.categories, required this.colors, required this.sources, required this.list});

  factory IndRegistry.parse(String json) {
    final j = (jsonDecode(json) as Map).cast<String, dynamic>();
    return IndRegistry(
      categories: [for (final c in (j['categories'] as List? ?? const [])) '$c'],
      colors: [for (final c in (j['colors'] as List? ?? const [])) '$c'],
      sources: [
        for (final s in (j['sources'] as List? ?? const []))
          if (s is Map) (value: '${s['value']}', label: '${s['label']}'),
      ],
      list: [for (final d in (j['indicators'] as List? ?? const [])) IndDef.fromJson((d as Map).cast<String, dynamic>())],
    );
  }

  final List<String> categories;
  final List<String> colors;
  final List<({String value, String label})> sources;
  final List<IndDef> list;

  IndDef? operator [](String type) {
    for (final d in list) {
      if (d.type == type) return d;
    }
    return null;
  }
}

/// The registry from the bundled asset.
final indicatorRegistryProvider = FutureProvider<IndRegistry>((ref) async => IndRegistry.parse(await rootBundle.loadString('assets/chart/indicators.json')));

/// One output's style override (web OutputStyle).
@immutable
class IndStyle {
  const IndStyle({this.color, this.width, this.visible});
  final String? color;
  final int? width;
  final bool? visible;

  bool get isEmpty => color == null && width == null && visible == null;

  Map<String, Object?> toJson() => {'color': ?color, 'width': ?width, if (visible == false) 'visible': false};

  static IndStyle fromJson(Object? j) {
    if (j is! Map) return const IndStyle();
    return IndStyle(color: j['color'] as String?, width: (j['width'] as num?)?.toInt(), visible: j['visible'] == false ? false : null);
  }
}

/// One indicator on a chart (web IndicatorInstance): what the chart page draws.
@immutable
class IndInstance {
  const IndInstance({required this.uid, required this.type, this.params = const {}, this.visible = true, this.style = const {}, this.levels});

  final String uid, type;
  final Map<String, Object> params;
  final bool visible;
  final Map<String, IndStyle> style;

  /// Custom levels (null: the indicator's defaults).
  final List<double>? levels;

  IndInstance copyWith({Map<String, Object>? params, bool? visible, Map<String, IndStyle>? style, List<double>? levels, bool clearLevels = false}) =>
      IndInstance(
        uid: uid,
        type: type,
        params: params ?? this.params,
        visible: visible ?? this.visible,
        style: style ?? this.style,
        levels: clearLevels ? null : (levels ?? this.levels),
      );

  Map<String, Object?> toJson() {
    final st = {
      for (final e in style.entries)
        if (!e.value.isEmpty) e.key: e.value.toJson(),
    };
    return {'uid': uid, 'type': type, 'params': params, 'visible': visible, if (st.isNotEmpty) 'style': st, 'levels': ?levels};
  }

  static IndInstance? fromJson(Object? j) {
    if (j is! Map || j['type'] is! String) return null;
    final p = j['params'];
    final st = j['style'];
    final lv = j['levels'];
    return IndInstance(
      uid: j['uid'] is String && (j['uid'] as String).isNotEmpty ? j['uid'] as String : newIndicatorUid(),
      type: j['type'] as String,
      params: {
        if (p is Map)
          for (final e in p.entries)
            if (e.value is num || e.value is String) '${e.key}': e.value as Object,
      },
      visible: j['visible'] != false,
      style: {
        if (st is Map)
          for (final e in st.entries) '${e.key}': IndStyle.fromJson(e.value),
      },
      levels: lv is List
          ? [
              for (final v in lv)
                if (v is num && v.isFinite) v.toDouble(),
            ]
          : null,
    );
  }

  @override
  bool operator ==(Object other) => other is IndInstance && jsonEncode(other.toJson()) == jsonEncode(toJson());

  @override
  int get hashCode => jsonEncode(toJson()).hashCode;
}

final _rnd = math.Random();

/// A short random id (web uid()).
String newIndicatorUid() => List.generate(8, (_) => '0123456789abcdefghijklmnopqrstuvwxyz'[_rnd.nextInt(36)]).join();

/// Params repaired to the definition (web normalizeParams): unknown keys dropped, numbers clamped, bad values -> defaults.
Map<String, Object> normalizeParams(IndDef d, Map<String, Object>? raw) {
  final out = <String, Object>{};
  for (final p in d.params) {
    final v = raw?[p.key];
    if (p.numeric) {
      final n = v is num ? v.toDouble() : (v is String ? double.tryParse(v) : null);
      if (n == null || !n.isFinite) {
        out[p.key] = p.def;
      } else {
        final c = n.clamp(p.min, p.max);
        out[p.key] = p.kind == 'int' ? c.round() : c;
      }
    } else if (p.kind == 'source') {
      out[p.key] = v is String && const ['close', 'open', 'high', 'low', 'hl2', 'hlc3', 'ohlc4'].contains(v) ? v : p.def;
    } else {
      out[p.key] = p.options.any((o) => o.value == v) ? v! : p.def;
    }
  }
  return out;
}

String _num(Object v) {
  if (v is double && v == v.roundToDouble()) return v.toInt().toString();
  return '$v';
}

/// "SMA 20", "BB 20, 2", "RSI 14 hlc3" (web indicatorLabel).
String indicatorLabel(IndDef d, Map<String, Object> params) {
  final parts = <String>[];
  var src = '';
  for (final p in d.params) {
    final v = params[p.key] ?? p.def;
    if (p.kind == 'source') {
      if (v != p.def) src = '$v';
    } else if (p.kind == 'select') {
      if (v != p.def) parts.add('$v'.toUpperCase());
    } else {
      parts.add(_num(v));
    }
  }
  return [d.short, parts.join(', '), src].where((s) => s.isNotEmpty).join(' ');
}

/// The label of an instance (the type in capitals until the registry is loaded).
String instanceLabel(IndRegistry? r, IndInstance i) {
  final d = r?[i.type];
  return d == null ? i.type.toUpperCase() : indicatorLabel(d, normalizeParams(d, i.params));
}

const _lineCycle = ['ember', 'gold', 'info', 'up', 'down', 'warn', 'fg2'];

/// A new instance (web makeInstance): a second line of the same single-line type gets the next free colour.
IndInstance makeInstance(IndRegistry r, String type, List<IndInstance> existing, {Map<String, Object>? params}) {
  final d = r[type]!;
  var inst = IndInstance(uid: newIndicatorUid(), type: type, params: normalizeParams(d, params));
  if (d.outputs.length == 1 && d.outputs.first.kind == 'line' && existing.any((e) => e.type == type)) {
    final used = <String>{
      for (final e in existing)
        if (r[e.type] case final ed? when ed.outputs.length == 1) e.style[ed.outputs.first.key]?.color ?? ed.outputs.first.color,
    };
    final col = _lineCycle.where((c) => !used.contains(c)).firstOrNull;
    if (col != null) inst = inst.copyWith(style: {d.outputs.first.key: IndStyle(color: col)});
  }
  return inst;
}

/// The web chart's default indicators (store.tsx defaultWorkspace: EMA 50, SMA 20).
List<IndInstance> defaultIndicators() => [
  IndInstance(uid: newIndicatorUid(), type: 'ema', params: const {'period': 50, 'source': 'close'}),
  IndInstance(uid: newIndicatorUid(), type: 'sma', params: const {'period': 20, 'source': 'close'}),
];

/// The web's indicator favourites until the client stars others (state.ts).
const kDefaultIndicatorFavourites = ['sma', 'ema', 'bb', 'rsi', 'macd'];

/// Chart types (web CHART_TYPES): labels `trader.chartType.<type>`.
const kChartTypes = ['candles', 'bars', 'line', 'area'];

/// A built-in chart template (web BUILTIN_TEMPLATES): label `chart.template.<id>`.
@immutable
class ChartTemplate {
  const ChartTemplate(this.id, this.type, this.indicators);
  final String id, type;

  /// (type, params, style)
  final List<(String, Map<String, Object>, Map<String, IndStyle>)> indicators;

  /// Fresh instances (new uids) for this template, params normalized against the registry.
  List<IndInstance> instances(IndRegistry? r) => [
    for (final (type, params, style) in indicators)
      IndInstance(uid: newIndicatorUid(), type: type, params: r?[type] == null ? params : normalizeParams(r![type]!, params), style: style),
  ];

  /// The chart already shows exactly this template (web templateMatches).
  bool matches(IndRegistry? r, String chartType, List<IndInstance> list) {
    if (chartType != type || list.length != indicators.length) return false;
    for (var i = 0; i < list.length; i++) {
      final (t, p, _) = indicators[i];
      final d = r?[t];
      if (list[i].type != t) return false;
      if (d != null && jsonEncode(normalizeParams(d, list[i].params)) != jsonEncode(normalizeParams(d, p))) return false;
    }
    return true;
  }
}

const kBuiltinTemplates = <ChartTemplate>[
  ChartTemplate('b-default', 'candles', []),
  ChartTemplate('b-trend', 'candles', [
    ('sma', {'period': 20}, {}),
    ('sma', {'period': 200}, {'ma': IndStyle(color: 'info')}),
    ('ema', {'period': 50}, {}),
  ]),
  ChartTemplate('b-vol', 'candles', [('bb', {}, {}), ('keltner', {}, {}), ('atr', {}, {})]),
  ChartTemplate('b-mom', 'candles', [('macd', {}, {}), ('rsi', {}, {})]),
  ChartTemplate('b-intraday', 'candles', [
    ('vwap', {}, {}),
    ('ema', {'period': 9}, {'ma': IndStyle(color: 'ember')}),
    ('ema', {'period': 21}, {}),
    ('stoch', {}, {}),
  ]),
  ChartTemplate('b-ichimoku', 'candles', [('ichimoku', {}, {})]),
  ChartTemplate('b-bw', 'candles', [('alligator', {}, {}), ('fractals', {}, {}), ('ao', {}, {}), ('ac', {}, {})]),
  ChartTemplate('b-line', 'line', []),
];
