// Crisp line icons (lucide), the same family as the web apps. Size 22 / stroke 1.75 by default in the app.
export {
  ArrowDownLeft,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowLeftRight,
  Bell,
  CandlestickChart,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  Clock,
  Copy,
  Eye,
  EyeOff,
  Globe,
  House,
  KeyRound,
  LayoutGrid,
  LineChart,
  Lock,
  LogOut,
  Mail,
  Minus,
  MoreHorizontal,
  Newspaper,
  Plus,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Star,
  TrendingDown,
  TrendingUp,
  User,
  Wallet,
  WifiOff,
  X,
  type LucideIcon,
} from "lucide-react-native";

export const ICON = { size: 22, stroke: 1.75 } as const;
