// Founder illustrations (assets/illustrations, generated by scripts/process-illustrations.mjs). The box has the
// image's exact aspect ratio, so nothing shifts when it decodes; expo-image caches in memory + on disk.
import * as React from "react";
import { View, type StyleProp, type ViewStyle } from "react-native";
import { Image } from "expo-image";
import { ILLUSTRATIONS, type IllustrationName } from "./illustrations.generated";

export type { IllustrationName };

export function Illustration({ name, width = 240, height, style }: { name: IllustrationName; width?: number; height?: number; style?: StyleProp<ViewStyle> }) {
  const it = ILLUSTRATIONS[name];
  // fit inside width x height when both are given
  let w = width;
  let h = w / it.aspect;
  if (height && h > height) {
    h = height;
    w = h * it.aspect;
  }
  return (
    <View style={[{ width: w, height: h }, style]} accessibilityElementsHidden importantForAccessibility="no-hide-descendants">
      <Image source={it.source} style={{ width: w, height: h }} contentFit="contain" cachePolicy="memory-disk" transition={0} recyclingKey={name} />
    </View>
  );
}
