// Generated by scripts/process-illustrations.mjs. Do not edit by hand.
/* eslint-disable */
import type { ImageSourcePropType } from "react-native";

export type IllustrationName = "welcome" | "security" | "market" | "kycPending" | "kycApproved" | "depositCredited" | "withdrawalProcessing" | "emptyHistory" | "emptyPosition" | "connectionLost" | "mascot" | "maintenance" | "copyTrading" | "emptyWatchlist" | "pammFunds" | "propChallenge" | "propPassed" | "rewards" | "partnerIb" | "marketClosed";

/** source + width / height (for layout without shift) + whether it is a placeholder awaiting the final art */
export const ILLUSTRATIONS: Record<IllustrationName, { source: ImageSourcePropType; aspect: number; placeholder: boolean }> = {
  welcome: { source: require("../../assets/illustrations/welcome.webp"), aspect: 0.6971, placeholder: false },
  security: { source: require("../../assets/illustrations/security.webp"), aspect: 1.0962, placeholder: false },
  market: { source: require("../../assets/illustrations/market.webp"), aspect: 1, placeholder: false },
  kycPending: { source: require("../../assets/illustrations/kycPending.webp"), aspect: 1.0097, placeholder: false },
  kycApproved: { source: require("../../assets/illustrations/kycApproved.webp"), aspect: 0.9887, placeholder: false },
  depositCredited: { source: require("../../assets/illustrations/depositCredited.webp"), aspect: 0.7266, placeholder: false },
  withdrawalProcessing: { source: require("../../assets/illustrations/withdrawalProcessing.webp"), aspect: 1.467, placeholder: false },
  emptyHistory: { source: require("../../assets/illustrations/emptyHistory.webp"), aspect: 1.5063, placeholder: false },
  emptyPosition: { source: require("../../assets/illustrations/emptyPosition.webp"), aspect: 1.6377, placeholder: false },
  connectionLost: { source: require("../../assets/illustrations/connectionLost.webp"), aspect: 1.3364, placeholder: false },
  mascot: { source: require("../../assets/illustrations/mascot.webp"), aspect: 0.605, placeholder: false },
  maintenance: { source: require("../../assets/illustrations/maintenance.webp"), aspect: 1.5, placeholder: false },
  copyTrading: { source: require("../../assets/illustrations/copyTrading.webp"), aspect: 1.1406, placeholder: true },
  emptyWatchlist: { source: require("../../assets/illustrations/emptyWatchlist.webp"), aspect: 1.1406, placeholder: true },
  pammFunds: { source: require("../../assets/illustrations/pammFunds.webp"), aspect: 1.1406, placeholder: true },
  propChallenge: { source: require("../../assets/illustrations/propChallenge.webp"), aspect: 1.1406, placeholder: true },
  propPassed: { source: require("../../assets/illustrations/propPassed.webp"), aspect: 1.1406, placeholder: true },
  rewards: { source: require("../../assets/illustrations/rewards.webp"), aspect: 1.1406, placeholder: true },
  partnerIb: { source: require("../../assets/illustrations/partnerIb.webp"), aspect: 1.1406, placeholder: true },
  marketClosed: { source: require("../../assets/illustrations/marketClosed.webp"), aspect: 1.1406, placeholder: true },
};
