import {
  Gauge,
  Users,
  CandlestickChart,
  SlidersHorizontal,
  Landmark,
  Handshake,
  Copy,
  Trophy,
  Megaphone,
  LifeBuoy,
  FileText,
  BarChart3,
  ShieldCheck,
  Building2,
  Globe2,
  Settings,
} from "lucide-react";
import type { NavModule } from "@kalks/ui";

/** Back Office navigation — the upgraded 16-section menu (plan: "Upgraded admin menu"). */
export const ADMIN_NAV: NavModule[] = [
  {
    key: "command",
    label: "Command Center",
    icon: Gauge,
    href: "/",
    match: ["/", "/command"],
    section: "ops",
    sub: [
      { href: "/", label: "Overview" },
      { href: "/command/risk", label: "Live risk" },
      { href: "/command/queues", label: "Queues", badge: 22 },
      { href: "/command/alerts", label: "Alerts", badge: 5 },
      { href: "/command/system", label: "System" },
    ],
  },
  {
    key: "clients",
    label: "Clients",
    icon: Users,
    href: "/clients",
    badge: 12,
    section: "ops",
    sub: [
      { href: "/clients", label: "Users" },
      { href: "/clients/leads", label: "Leads" },
      { href: "/clients/kyc", label: "KYC queue", badge: 12 },
      { href: "/clients/aml", label: "AML cases", badge: 2 },
      { href: "/clients/duplicates", label: "Duplicates" },
      { href: "/clients/segments", label: "Segments" },
    ],
  },
  {
    key: "trading",
    label: "Trading",
    icon: CandlestickChart,
    href: "/trading",
    section: "ops",
    sub: [
      { href: "/trading", label: "Positions" },
      { href: "/trading/orders", label: "Orders" },
      { href: "/trading/accounts", label: "Accounts" },
      { href: "/trading/routing", label: "Book & routing" },
      { href: "/trading/exposure", label: "Exposure" },
      { href: "/trading/dealer", label: "Dealer desk" },
      { href: "/trading/rollovers", label: "Rollovers" },
      { href: "/trading/corporate-actions", label: "Corporate actions" },
    ],
  },
  {
    key: "config",
    label: "Config",
    icon: SlidersHorizontal,
    href: "/config",
    section: "ops",
    sub: [
      { href: "/config", label: "Account groups" },
      { href: "/config/symbols", label: "Symbols" },
      { href: "/config/spreads", label: "Spreads" },
      { href: "/config/charges", label: "Charges" },
      { href: "/config/swaps", label: "Swaps" },
      { href: "/config/margin", label: "Margin schedules" },
      { href: "/config/sessions", label: "Sessions & holidays" },
      { href: "/config/demo", label: "Demo rules" },
    ],
  },
  {
    key: "finance",
    label: "Finance",
    icon: Landmark,
    href: "/finance",
    badge: 7,
    section: "money",
    sub: [
      { href: "/finance", label: "Deposits" },
      { href: "/finance/withdrawals", label: "Withdrawals", badge: 7 },
      { href: "/finance/wallets", label: "Wallets" },
      { href: "/finance/reconciliation", label: "Reconciliation" },
      { href: "/finance/transactions", label: "Transactions" },
      { href: "/finance/adjustments", label: "Adjustments" },
      { href: "/finance/payouts", label: "Payouts", badge: 3 },
      { href: "/finance/conversion", label: "Conversion" },
    ],
  },
  {
    key: "partners",
    label: "Partners",
    icon: Handshake,
    href: "/partners",
    section: "money",
    sub: [
      { href: "/partners", label: "IB overview" },
      { href: "/partners/list", label: "Partners" },
      { href: "/partners/plans", label: "Commission plans" },
      { href: "/partners/levels", label: "Levels" },
      { href: "/partners/sub-brokers", label: "Sub-brokers" },
      { href: "/partners/fraud", label: "Fraud flags" },
      { href: "/partners/commissions", label: "Commissions" },
      { href: "/partners/payouts", label: "Payout batches" },
    ],
  },
  {
    key: "social",
    label: "Social & Algo",
    icon: Copy,
    href: "/social",
    section: "money",
    sub: [
      { href: "/social", label: "Masters" },
      { href: "/social/pamm", label: "PAMM funds" },
      { href: "/social/applications", label: "Applications" },
      { href: "/social/marketplace", label: "Marketplace" },
      { href: "/social/api-keys", label: "API keys" },
      { href: "/social/settings", label: "Fee caps" },
    ],
  },
  {
    key: "prop",
    label: "Prop Firm",
    icon: Trophy,
    href: "/prop",
    section: "money",
    sub: [
      { href: "/prop", label: "Overview" },
      { href: "/prop/plans", label: "Plan builder" },
      { href: "/prop/challenges", label: "Challenges" },
      { href: "/prop/funded", label: "Funded traders" },
      { href: "/prop/payouts", label: "Payouts" },
      { href: "/prop/violations", label: "Violations" },
    ],
  },
  {
    key: "marketing",
    label: "Marketing",
    icon: Megaphone,
    href: "/marketing",
    section: "growth",
    sub: [
      { href: "/marketing", label: "Bonuses" },
      { href: "/marketing/banners", label: "Banners" },
      { href: "/marketing/contests", label: "Contests" },
      { href: "/marketing/rewards", label: "Rewards" },
      { href: "/marketing/automation", label: "Automation" },
      { href: "/marketing/promo-codes", label: "Promo codes" },
      { href: "/marketing/campaigns", label: "Campaigns" },
    ],
  },
  {
    key: "support",
    label: "Support",
    icon: LifeBuoy,
    href: "/support",
    badge: 4,
    section: "growth",
    sub: [
      { href: "/support", label: "Inbox", badge: 4 },
      { href: "/support/knowledge", label: "AI knowledge base" },
      { href: "/support/canned", label: "Canned replies" },
      { href: "/support/csat", label: "CSAT" },
    ],
  },
  {
    key: "content",
    label: "Content",
    icon: FileText,
    href: "/content",
    section: "growth",
    sub: [
      { href: "/content", label: "News" },
      { href: "/content/legal", label: "Legal documents" },
      { href: "/content/emails", label: "Email templates" },
      { href: "/content/notifications", label: "Notifications" },
      { href: "/content/academy", label: "Academy" },
      { href: "/content/translations", label: "Translations" },
    ],
  },
  {
    key: "analytics",
    label: "Analytics",
    icon: BarChart3,
    href: "/analytics",
    section: "insight",
    sub: [
      { href: "/analytics", label: "Broker P&L" },
      { href: "/analytics/funnel", label: "Funnel" },
      { href: "/analytics/cohorts", label: "Cohorts & LTV" },
      { href: "/analytics/deposits", label: "Deposits" },
      { href: "/analytics/partners", label: "Partners" },
      { href: "/analytics/regulatory", label: "Regulatory" },
      { href: "/analytics/scheduled", label: "Scheduled reports" },
    ],
  },
  {
    key: "security",
    label: "Security & Audit",
    icon: ShieldCheck,
    href: "/security",
    section: "insight",
    sub: [
      { href: "/security", label: "Admin audit log" },
      { href: "/security/users", label: "User activity" },
      { href: "/security/sessions", label: "Staff sessions" },
      { href: "/security/ip", label: "IP whitelist" },
    ],
  },
  {
    key: "org",
    label: "Organization",
    icon: Building2,
    href: "/org",
    section: "insight",
    sub: [
      { href: "/org", label: "Employees" },
      { href: "/org/roles", label: "Roles & permissions" },
      { href: "/org/desks", label: "Desks & teams" },
      { href: "/org/kpis", label: "KPIs & commissions" },
    ],
  },
  {
    key: "brokers",
    label: "Brokers (Owner)",
    icon: Globe2,
    href: "/brokers",
    section: "owner",
    sub: [
      { href: "/brokers", label: "Tenants" },
      { href: "/brokers/billing", label: "Billing" },
      { href: "/brokers/modules", label: "Modules & plans" },
      { href: "/brokers/symbols", label: "Global symbols" },
      { href: "/brokers/system", label: "System ops" },
      { href: "/brokers/flags", label: "Feature flags" },
    ],
  },
  {
    key: "settings",
    label: "Settings",
    icon: Settings,
    href: "/settings",
    section: "owner",
    sub: [
      { href: "/settings", label: "General & branding" },
      { href: "/settings/integrations", label: "Integrations" },
      { href: "/settings/payments", label: "Payment methods" },
      { href: "/settings/countries", label: "Countries" },
      { href: "/settings/webhooks", label: "Webhooks" },
      { href: "/settings/maintenance", label: "Maintenance" },
    ],
  },
];

export const ADMIN_COMMANDS = ADMIN_NAV.flatMap((m) => (m.sub ?? [{ href: m.href, label: m.label }]).map((s) => ({ group: m.label, label: s.label, href: s.href, Icon: m.icon })));
