use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use markethours::{Holidays, Session};
use std::collections::HashMap;
use std::sync::Arc;

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Provider {
    pub market: String, // common | crypto | stock
    pub code: String,
}

/// One instrument of `config/instruments.json`. The 28 core instruments carry only the original fields; the
/// provider catalogue rows (`"tier": "catalogue"`, generated by `scripts/gen-catalogue.mjs`) add a name, the
/// currencies, the exchange, a holiday calendar and the spec template the trading engine uses for them.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Instrument {
    pub symbol: String,
    pub asset_class: String,
    pub digits: u32,
    pub base_spread: f64,
    pub provider: Provider,
    /// Trading session: `fx` (closed Saturday and Sunday server time), `24x7`, or exchange hours (`us_equity`
    /// 09:30–16:00 New York, `hk_equity`, ...; extended-hours trades are ignored so bars match the exchange's
    /// regular-session candles). None = `24x7` for crypto, `fx` otherwise.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session: Option<String>,
    /// `catalogue` for provider-catalogue rows; absent for the core instruments.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tier: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_ccy: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quote_ccy: Option<String>,
    /// Listing exchange / venue (stocks, indices).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exchange: Option<String>,
    /// Holiday calendar closing the session (config/holidays, config/holidays/exchanges).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub calendar: Option<String>,
    /// Spec template of the trading engine (config/trading-specs.json `templates`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub template: Option<String>,
    /// Pip size when it is not the usual one for the digits (catalogue FX).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pip_size: Option<f64>,
    #[serde(skip)]
    pub sched: Option<Sched>,
}

/// Resolved session + holiday calendar (filled in by `Catalogue::from_list`).
#[derive(Clone, Debug)]
pub struct Sched {
    pub session: Session,
    pub holidays: Option<Arc<Holidays>>,
}

impl Instrument {
    pub fn point(&self) -> f64 {
        10f64.powi(-(self.digits as i32))
    }

    /// One of the hand-maintained core instruments.
    pub fn is_core(&self) -> bool {
        self.tier.as_deref() != Some("catalogue")
    }

    /// The session without a calendar, exactly as before the catalogue existed: `us_equity`, crypto around the
    /// clock, everything else (FX, metals, indices, energies) closed over the weekend (Saturday and Sunday server
    /// time, i.e. New York Friday 17:00 to Sunday 17:00): stray provider quotes in that window are not market prices.
    fn default_session(&self) -> Session {
        match self.session.as_deref() {
            Some(s) if Session::parse(s).is_some() => Session::parse(s).unwrap(),
            _ if self.asset_class == "crypto" => Session::Always,
            _ => Session::Fx,
        }
    }

    pub fn in_session(&self, ts: DateTime<Utc>) -> bool {
        match &self.sched {
            Some(s) => s.session.is_open(ts, s.holidays.as_deref()),
            None => self.default_session().is_open(ts, None),
        }
    }

    pub fn round_bar(&self, b: crate::db::Bar) -> crate::db::Bar {
        crate::db::Bar { o: self.round(b.o), h: self.round(b.h), l: self.round(b.l), c: self.round(b.c), ..b }
    }

    pub fn round(&self, p: f64) -> f64 {
        let f = 10f64.powi(self.digits as i32);
        (p * f).round() / f
    }
}

/// Instrument catalogue with lookups in both directions (Kalks symbol ↔ provider market+code).
#[derive(Clone, Debug)]
pub struct Catalogue {
    pub list: Vec<Instrument>,
    by_symbol: HashMap<String, usize>,
    by_provider: HashMap<(String, String), usize>,
}

impl Catalogue {
    /// Loads the instrument file; holiday calendars come from `holidays_dir` (config/holidays).
    pub fn load(path: &str, holidays_dir: &str) -> anyhow::Result<Self> {
        let raw = std::fs::read_to_string(path).map_err(|e| anyhow::anyhow!("reading {path}: {e}"))?;
        let list: Vec<Instrument> = serde_json::from_str(&raw)?;
        let calendars = Holidays::load_dir(holidays_dir).map_err(|e| anyhow::anyhow!("holiday calendars: {e}"))?;
        Self::with_calendars(list, &calendars)
    }

    /// A catalogue without holiday calendars (rows naming one are refused).
    #[cfg(test)]
    pub fn from_list(list: Vec<Instrument>) -> anyhow::Result<Self> {
        Self::with_calendars(list, &HashMap::new())
    }

    /// Validates the rows (unique symbols and provider codes, known sessions and calendars) and resolves their
    /// trading schedule.
    pub fn with_calendars(mut list: Vec<Instrument>, calendars: &HashMap<String, Holidays>) -> anyhow::Result<Self> {
        let cals: HashMap<&str, Arc<Holidays>> = calendars.iter().map(|(k, v)| (k.as_str(), Arc::new(v.clone()))).collect();
        let mut by_symbol = HashMap::new();
        let mut by_provider = HashMap::new();
        for (i, x) in list.iter_mut().enumerate() {
            if x.symbol.is_empty() || x.provider.code.is_empty() || x.provider.market.is_empty() {
                anyhow::bail!("instrument #{i}: symbol and provider market / code are required");
            }
            if x.digits > 10 {
                anyhow::bail!("{}: digits {} out of range", x.symbol, x.digits);
            }
            if let Some(s) = &x.session
                && Session::parse(s).is_none()
            {
                anyhow::bail!("{}: unknown session {s}", x.symbol);
            }
            let holidays = match &x.calendar {
                Some(c) => Some(cals.get(c.as_str()).cloned().ok_or_else(|| anyhow::anyhow!("{}: holiday calendar {c} not found", x.symbol))?),
                None => None,
            };
            x.sched = Some(Sched { session: x.default_session(), holidays });
            if by_symbol.insert(x.symbol.clone(), i).is_some() {
                anyhow::bail!("{}: listed twice", x.symbol);
            }
            if let Some(j) = by_provider.insert((x.provider.market.clone(), x.provider.code.clone()), i) {
                anyhow::bail!("{} and {}: same provider code {}/{}", list_symbol(&by_symbol, j), x.symbol, x.provider.market, x.provider.code);
            }
        }
        Ok(Self { list, by_symbol, by_provider })
    }

    pub fn get(&self, symbol: &str) -> Option<&Instrument> {
        self.by_symbol.get(symbol).map(|&i| &self.list[i])
    }
    pub fn from_provider(&self, market: &str, code: &str) -> Option<&Instrument> {
        self.by_provider.get(&(market.to_string(), code.to_string())).map(|&i| &self.list[i])
    }
    pub fn markets(&self) -> Vec<String> {
        let mut m: Vec<String> = self.list.iter().map(|x| x.provider.market.clone()).collect();
        m.sort();
        m.dedup();
        m
    }
    /// The symbol converting `ccy` to USD (core instruments first, like the trading engine).
    pub fn usd_pair(&self, ccy: &str) -> Option<String> {
        for core in [true, false] {
            for s in [format!("{ccy}USD"), format!("USD{ccy}")] {
                if self.get(&s).is_some_and(|i| i.is_core() == core) {
                    return Some(s);
                }
            }
        }
        None
    }

    /// The core instruments' symbols.
    pub fn core(&self) -> Vec<String> {
        self.list.iter().filter(|x| x.is_core()).map(|x| x.symbol.clone()).collect()
    }
}

fn list_symbol(by_symbol: &HashMap<String, usize>, i: usize) -> String {
    by_symbol.iter().find(|(_, v)| **v == i).map(|(k, _)| k.clone()).unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;

    fn stock() -> Instrument {
        Instrument {
            symbol: "AAPL".into(),
            asset_class: "stocks".into(),
            digits: 2,
            base_spread: 0.06,
            provider: Provider { market: "stock".into(), code: "AAPL.US".into() },
            session: Some("us_equity".into()),
            ..Default::default()
        }
    }

    #[test]
    fn us_equity_session() {
        let s = stock();
        // September (EDT, UTC−4): regular session 13:30–20:00 UTC
        assert!(!s.in_session(Utc.with_ymd_and_hms(2026, 9, 24, 13, 29, 59).unwrap()));
        assert!(s.in_session(Utc.with_ymd_and_hms(2026, 9, 24, 13, 30, 0).unwrap()));
        assert!(s.in_session(Utc.with_ymd_and_hms(2026, 9, 24, 19, 59, 59).unwrap()));
        assert!(!s.in_session(Utc.with_ymd_and_hms(2026, 9, 24, 20, 0, 0).unwrap()));
        // January (EST, UTC−5): 14:30–21:00 UTC
        assert!(!s.in_session(Utc.with_ymd_and_hms(2026, 1, 14, 14, 0, 0).unwrap()));
        assert!(s.in_session(Utc.with_ymd_and_hms(2026, 1, 14, 20, 30, 0).unwrap()));
        // weekend
        assert!(!s.in_session(Utc.with_ymd_and_hms(2026, 9, 26, 15, 0, 0).unwrap()));
    }

    #[test]
    fn fx_weekend_close() {
        let fx = Instrument { symbol: "EURUSD".into(), asset_class: "forex".into(), digits: 5, base_spread: 0.0001, provider: Provider { market: "common".into(), code: "EURUSD".into() }, ..Default::default() };
        // September (server GMT+3): Friday 20:59 UTC trades, Friday 21:00 UTC (Sat 00:00 server) is closed
        assert!(fx.in_session(Utc.with_ymd_and_hms(2026, 9, 25, 20, 59, 59).unwrap()));
        assert!(!fx.in_session(Utc.with_ymd_and_hms(2026, 9, 25, 21, 0, 0).unwrap()));
        assert!(!fx.in_session(Utc.with_ymd_and_hms(2026, 9, 26, 9, 0, 0).unwrap()));
        assert!(!fx.in_session(Utc.with_ymd_and_hms(2026, 9, 27, 20, 59, 0).unwrap()));
        // reopens Sunday 21:00 UTC (Monday 00:00 server)
        assert!(fx.in_session(Utc.with_ymd_and_hms(2026, 9, 27, 21, 0, 0).unwrap()));
        // January (server GMT+2): reopens Sunday 22:00 UTC
        assert!(!fx.in_session(Utc.with_ymd_and_hms(2026, 1, 11, 21, 30, 0).unwrap()));
        assert!(fx.in_session(Utc.with_ymd_and_hms(2026, 1, 11, 22, 0, 0).unwrap()));
        let btc = Instrument { asset_class: "crypto".into(), ..fx };
        assert!(btc.in_session(Utc.with_ymd_and_hms(2026, 9, 26, 9, 0, 0).unwrap()));
    }

    #[test]
    fn catalogue_validation() {
        let a = stock();
        let dup_symbol = Catalogue::from_list(vec![a.clone(), a.clone()]);
        assert!(dup_symbol.is_err());
        let b = Instrument { symbol: "AAPL2".into(), ..a.clone() };
        assert!(Catalogue::from_list(vec![a.clone(), b]).unwrap_err().to_string().contains("same provider code"));
        let bad_session = Instrument { session: Some("moon".into()), ..a.clone() };
        assert!(Catalogue::from_list(vec![bad_session]).is_err());
        let no_calendar = Instrument { calendar: Some("NOPE".into()), ..a.clone() };
        assert!(Catalogue::from_list(vec![no_calendar]).unwrap_err().to_string().contains("calendar"));
        let c = Catalogue::from_list(vec![a]).unwrap();
        assert_eq!(c.from_provider("stock", "AAPL.US").unwrap().symbol, "AAPL");
        assert_eq!(c.core(), vec!["AAPL".to_string()]);
    }
}
